/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import bean.Clientes;
import dao.ClientesDAO;
import javax.swing.JOptionPane;
import tools.Util_GME;

/**
 *
 * @author guilh
 */
public class JDlgClientes_GME extends javax.swing.JDialog {

    /**
     * Creates new form jDlgClientes
     */
    public JDlgClientes_GME(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Tela de Cadastro de Clientes");
        setLocationRelativeTo(null);
        Util_GME.habilitar(false, jTxtCodigo_GME, jTxtCargo_GME, jTxtCodigo_GME, jTxtEmailLoja_GME, jTxtEmail_pessoal_GME,
                jTxtNomeLoja_GME, jTxtNomePessoal_GME, jTxtnumero_GME, jFmt_CEP_GME, jFmt_CNPJ_GME, jFmt_DataCadastro_GME,
                jFmt_Datanasc_GME, jFmt_telefone_loja_GME, jFmt_telefone_pessoal_GME, jCbxEstadoCivil_GME, jCbxGenero_GME,
                 jBtnConfirmar_GME, jBtnExcluir_GME, jBtnCancelar_GME);
    }

    private boolean incluir;
    private boolean pesquisar;

    public Clientes viewBean() {
        Clientes clientes = new Clientes();
        int codigo = Util_GME.strToInt(jTxtCodigo_GME.getText());
        clientes.setGmeIdClientes(codigo);
        clientes.setGmeNomePessoal(jTxtNomePessoal_GME.getText());
        clientes.setGmeEmailPessoal(jTxtEmail_pessoal_GME.getText());
        clientes.setGmeTelefonePessoal(jFmt_telefone_pessoal_GME.getText());
        clientes.setGmeDatanasc(Util_GME.strToDate(jFmt_Datanasc_GME.getText()));
        clientes.setGmeGenero(jCbxGenero_GME.getSelectedIndex());
        clientes.setGmeEstadocivil(jCbxEstadoCivil_GME.getSelectedIndex());
        clientes.setGmeCargo(jTxtCargo_GME.getText());
        clientes.setGmeNomeLoja(jTxtNomeLoja_GME.getText());
        clientes.setGmeEmailLoja(jTxtEmailLoja_GME.getText());
        clientes.setGmeTelefoneLoja(jFmt_telefone_loja_GME.getText());
        clientes.setGmeDataCadastro(Util_GME.strToDate(jFmt_DataCadastro_GME.getText()));
        clientes.setGmeCnpj(jFmt_CNPJ_GME.getText());
        clientes.setGmeCep(jFmt_CEP_GME.getText());
        clientes.setGmeNumero(jTxtnumero_GME.getText());

        return clientes;
    }

    public void beanView(Clientes clientes) {
        jTxtCodigo_GME.setText(Util_GME.intToStr(clientes.getGmeIdClientes()));
        jTxtCargo_GME.setText(clientes.getGmeCargo());
        jTxtEmailLoja_GME.setText(clientes.getGmeEmailLoja());
        jTxtEmail_pessoal_GME.setText(clientes.getGmeEmailPessoal());
        jTxtNomeLoja_GME.setText(clientes.getGmeNomeLoja());
        jTxtNomePessoal_GME.setText(clientes.getGmeNomePessoal());
        jTxtnumero_GME.setText(clientes.getGmeNumero());

        jCbxEstadoCivil_GME.setSelectedIndex(clientes.getGmeEstadocivil());
        jCbxGenero_GME.setSelectedIndex(clientes.getGmeGenero());

        jFmt_CEP_GME.setText(clientes.getGmeCep());
        jFmt_CNPJ_GME.setText(clientes.getGmeCnpj());
        jFmt_telefone_pessoal_GME.setText(clientes.getGmeTelefonePessoal());
        jFmt_telefone_loja_GME.setText(clientes.getGmeTelefoneLoja());
        jFmt_Datanasc_GME.setText(Util_GME.dateToStr(clientes.getGmeDatanasc()));
        jFmt_DataCadastro_GME.setText(Util_GME.dateToStr(clientes.getGmeDataCadastro()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telefonePessoal_GME = new javax.swing.JLabel();
        TelefoneLoJa_GME = new javax.swing.JLabel();
        emailpessoal_GME = new javax.swing.JLabel();
        data_de_Cadastro_GME = new javax.swing.JLabel();
        Cargo_GME = new javax.swing.JLabel();
        jTxtCargo_GME = new javax.swing.JTextField();
        data_de_nascimento_GME = new javax.swing.JLabel();
        Estado_civil_GME = new javax.swing.JLabel();
        jBtnConfirmar_GME = new javax.swing.JButton();
        genero_GME = new javax.swing.JLabel();
        jBtnExcluir_GME = new javax.swing.JButton();
        numero_GME = new javax.swing.JLabel();
        jBtnCancelar_GME = new javax.swing.JButton();
        jTxtnumero_GME = new javax.swing.JTextField();
        jBtnPesquisar_GME = new javax.swing.JButton();
        CEP_GME = new javax.swing.JLabel();
        jBtnAlterar_GME = new javax.swing.JButton();
        jCbxGenero_GME = new javax.swing.JComboBox<>();
        jBtnIncluir_GME = new javax.swing.JButton();
        jCbxEstadoCivil_GME = new javax.swing.JComboBox<>();
        nomepessoal_GME = new javax.swing.JLabel();
        jTxtNomePessoal_GME = new javax.swing.JTextField();
        codigo_GME = new javax.swing.JLabel();
        jTxtCodigo_GME = new javax.swing.JTextField();
        NomeLoja_GME = new javax.swing.JLabel();
        jFmt_Datanasc_GME = new javax.swing.JFormattedTextField();
        jTxtNomeLoja_GME = new javax.swing.JTextField();
        jFmt_DataCadastro_GME = new javax.swing.JFormattedTextField();
        CNPJ_GME = new javax.swing.JLabel();
        jFmt_telefone_pessoal_GME = new javax.swing.JFormattedTextField();
        jTxtEmail_pessoal_GME = new javax.swing.JTextField();
        jFmt_telefone_loja_GME = new javax.swing.JFormattedTextField();
        EmailLoja_GME = new javax.swing.JLabel();
        jFmt_CNPJ_GME = new javax.swing.JFormattedTextField();
        jTxtEmailLoja_GME = new javax.swing.JTextField();
        jFmt_CEP_GME = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        telefonePessoal_GME.setText("Telefone Pessoal");

        TelefoneLoJa_GME.setText("Telefone Loja");

        emailpessoal_GME.setText("Email Pessoal");

        data_de_Cadastro_GME.setText("Data de Cadastro");

        Cargo_GME.setText("Cargo");

        data_de_nascimento_GME.setText("Data de Nascimento");

        Estado_civil_GME.setText("Estado Civil");

        jBtnConfirmar_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/OK2.0.png"))); // NOI18N
        jBtnConfirmar_GME.setText("Confirmar");
        jBtnConfirmar_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmar_GMEActionPerformed(evt);
            }
        });

        genero_GME.setText("Gênero");

        jBtnExcluir_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novoExcluir.png"))); // NOI18N
        jBtnExcluir_GME.setText("Excluir");
        jBtnExcluir_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluir_GMEActionPerformed(evt);
            }
        });

        numero_GME.setText("Numero");

        jBtnCancelar_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novoCANCELAR.png"))); // NOI18N
        jBtnCancelar_GME.setText("Cancelar");
        jBtnCancelar_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelar_GMEActionPerformed(evt);
            }
        });

        jBtnPesquisar_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novoPESQUISAR.png"))); // NOI18N
        jBtnPesquisar_GME.setText("Pesquisar");
        jBtnPesquisar_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisar_GMEActionPerformed(evt);
            }
        });

        CEP_GME.setText("CEP");

        jBtnAlterar_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novoalterar.png"))); // NOI18N
        jBtnAlterar_GME.setText("Alterar");
        jBtnAlterar_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterar_GMEActionPerformed(evt);
            }
        });

        jCbxGenero_GME.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "masculino", "feminino" }));
        jCbxGenero_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbxGenero_GMEActionPerformed(evt);
            }
        });

        jBtnIncluir_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novoincluir.png"))); // NOI18N
        jBtnIncluir_GME.setText("Incluir");
        jBtnIncluir_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluir_GMEActionPerformed(evt);
            }
        });

        jCbxEstadoCivil_GME.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro", "Casado" }));
        jCbxEstadoCivil_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbxEstadoCivil_GMEActionPerformed(evt);
            }
        });

        nomepessoal_GME.setText("Nome Pessoal");

        jTxtNomePessoal_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNomePessoal_GMEActionPerformed(evt);
            }
        });

        codigo_GME.setText("Código [ID]");

        NomeLoja_GME.setText("Nome da Loja");

        try {
            jFmt_Datanasc_GME.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFmt_DataCadastro_GME.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        CNPJ_GME.setText("CNPJ");

        try {
            jFmt_telefone_pessoal_GME.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##).#.####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFmt_telefone_loja_GME.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##).#.####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        EmailLoja_GME.setText("Email Loja");

        try {
            jFmt_CNPJ_GME.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFmt_CEP_GME.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomepessoal_GME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtNomePessoal_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Cargo_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 28, Short.MAX_VALUE))
                            .addComponent(jBtnIncluir_GME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAlterar_GME, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnExcluir_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jBtnConfirmar_GME)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCancelar_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnPesquisar_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtCargo_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genero_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCbxGenero_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telefonePessoal_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFmt_telefone_pessoal_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(data_de_nascimento_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jFmt_Datanasc_GME, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Estado_civil_GME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCbxEstadoCivil_GME, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTxtEmail_pessoal_GME))
                                .addGap(197, 197, 197))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(emailpessoal_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TelefoneLoJa_GME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(CNPJ_GME, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                            .addComponent(jTxtNomeLoja_GME)
                                            .addComponent(NomeLoja_GME, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                            .addComponent(jFmt_telefone_loja_GME))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jFmt_CNPJ_GME)
                                        .addGap(6, 6, 6)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EmailLoja_GME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTxtEmailLoja_GME)
                                    .addComponent(jTxtCodigo_GME)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(data_de_Cadastro_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(codigo_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jFmt_DataCadastro_GME, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jFmt_CEP_GME, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                    .addComponent(CEP_GME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(numero_GME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(76, 76, 76))
                                    .addComponent(jTxtnumero_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomepessoal_GME)
                            .addComponent(emailpessoal_GME))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtNomePessoal_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtEmail_pessoal_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telefonePessoal_GME)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(data_de_nascimento_GME)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFmt_Datanasc_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Cargo_GME)
                                    .addComponent(Estado_civil_GME))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCbxEstadoCivil_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtCargo_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(genero_GME)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCbxGenero_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NomeLoja_GME)
                            .addComponent(codigo_GME))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtNomeLoja_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtCodigo_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TelefoneLoJa_GME)
                                    .addComponent(EmailLoja_GME))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFmt_telefone_pessoal_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTxtEmailLoja_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jFmt_telefone_loja_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(12, 12, 12)
                                .addComponent(CNPJ_GME)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFmt_DataCadastro_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFmt_CNPJ_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(data_de_Cadastro_GME)
                                .addGap(28, 28, 28)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numero_GME)
                            .addComponent(CEP_GME))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtnumero_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmt_CEP_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnExcluir_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnCancelar_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnPesquisar_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnConfirmar_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBtnIncluir_GME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnAlterar_GME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnConfirmar_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmar_GMEActionPerformed
        pesquisar = false;
        
        ClientesDAO clientesDAO = new ClientesDAO();
        if (incluir == true) {

            clientesDAO.insert(viewBean());

        } else {

            clientesDAO.update(viewBean());
        }

        Util_GME.Limpar(jTxtCodigo_GME, jTxtCargo_GME, jTxtCodigo_GME, jTxtEmailLoja_GME, jTxtEmail_pessoal_GME,
                jTxtNomeLoja_GME, jTxtNomePessoal_GME, jTxtnumero_GME, jFmt_CEP_GME, jFmt_CNPJ_GME, jFmt_DataCadastro_GME,
                jFmt_Datanasc_GME, jFmt_telefone_loja_GME, jFmt_telefone_pessoal_GME, jCbxEstadoCivil_GME, jCbxGenero_GME);

        Util_GME.habilitar(false, jTxtCodigo_GME, jTxtCargo_GME, jTxtCodigo_GME, jTxtEmailLoja_GME, jTxtEmail_pessoal_GME,
                jTxtNomeLoja_GME, jTxtNomePessoal_GME, jTxtnumero_GME,
                jFmt_CEP_GME, jFmt_CNPJ_GME, jFmt_DataCadastro_GME, jFmt_Datanasc_GME, jFmt_telefone_loja_GME, jFmt_telefone_pessoal_GME,
                jCbxEstadoCivil_GME, jCbxGenero_GME,
                 jBtnConfirmar_GME, jBtnCancelar_GME, jBtnExcluir_GME
        );
        Util_GME.habilitar(true, jBtnIncluir_GME, jBtnPesquisar_GME,jBtnAlterar_GME);
    }//GEN-LAST:event_jBtnConfirmar_GMEActionPerformed

    private void jBtnExcluir_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluir_GMEActionPerformed
        if (Util_GME.perguntar("Deseja excluir esse registro de Clientes?") == true) {

            ClientesDAO clientesDAO = new ClientesDAO();
            clientesDAO.delete(viewBean());

            Util_GME.Limpar(jTxtCodigo_GME, jTxtCargo_GME, jTxtCodigo_GME, jTxtEmailLoja_GME, jTxtEmail_pessoal_GME,
                    jTxtNomeLoja_GME, jTxtNomePessoal_GME, jTxtnumero_GME, jFmt_CEP_GME, jFmt_CNPJ_GME, jFmt_DataCadastro_GME,
                    jFmt_Datanasc_GME, jFmt_telefone_loja_GME, jFmt_telefone_pessoal_GME, jCbxEstadoCivil_GME, jCbxGenero_GME);

            Util_GME.habilitar(false, jTxtCodigo_GME, jTxtCargo_GME, jTxtCodigo_GME, jTxtEmailLoja_GME, jTxtEmail_pessoal_GME,
                    jTxtNomeLoja_GME, jTxtNomePessoal_GME, jTxtnumero_GME,
                    jFmt_CEP_GME, jFmt_CNPJ_GME, jFmt_DataCadastro_GME, jFmt_Datanasc_GME, jFmt_telefone_loja_GME, jFmt_telefone_pessoal_GME,
                    jCbxEstadoCivil_GME, jCbxGenero_GME,
                     jBtnConfirmar_GME, jBtnCancelar_GME, jBtnExcluir_GME
            );
            Util_GME.habilitar(true, jBtnIncluir_GME, jBtnPesquisar_GME,jBtnAlterar_GME);
        } else {
        }

    }//GEN-LAST:event_jBtnExcluir_GMEActionPerformed

    private void jBtnCancelar_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelar_GMEActionPerformed

        if (Util_GME.perguntar("Deseja cancelar esse registro de Clientes?") == true) {
            pesquisar = false;
            Util_GME.Limpar(jTxtCodigo_GME, jTxtCargo_GME, jTxtCodigo_GME, jTxtEmailLoja_GME, jTxtEmail_pessoal_GME,
                    jTxtNomeLoja_GME, jTxtNomePessoal_GME, jTxtnumero_GME, jFmt_CEP_GME, jFmt_CNPJ_GME, jFmt_DataCadastro_GME,
                    jFmt_Datanasc_GME, jFmt_telefone_loja_GME, jFmt_telefone_pessoal_GME, jCbxEstadoCivil_GME, jCbxGenero_GME);

            Util_GME.habilitar(false, jTxtCodigo_GME, jTxtCargo_GME, jTxtCodigo_GME, jTxtEmailLoja_GME, jTxtEmail_pessoal_GME,
                    jTxtNomeLoja_GME, jTxtNomePessoal_GME, jTxtnumero_GME,
                    jFmt_CEP_GME, jFmt_CNPJ_GME, jFmt_DataCadastro_GME, jFmt_Datanasc_GME, jFmt_telefone_loja_GME, jFmt_telefone_pessoal_GME,
                    jCbxEstadoCivil_GME, jCbxGenero_GME,
                     jBtnConfirmar_GME, jBtnCancelar_GME, jBtnExcluir_GME
            );
            Util_GME.habilitar(true, jBtnIncluir_GME, jBtnPesquisar_GME, jBtnAlterar_GME);
        } else {
        }
    }//GEN-LAST:event_jBtnCancelar_GMEActionPerformed

    private void jBtnPesquisar_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisar_GMEActionPerformed
        pesquisar = true;
        
        JDlgClientesPesquisar_GME jDlgClientesPesquisar_GME = new JDlgClientesPesquisar_GME(null, true);
        jDlgClientesPesquisar_GME.setTelaAnterior(this);
        jDlgClientesPesquisar_GME.setVisible(true);

        Util_GME.habilitar(false, jTxtCodigo_GME, jTxtCargo_GME, jTxtCodigo_GME, jTxtEmailLoja_GME, jTxtEmail_pessoal_GME,
                jTxtNomeLoja_GME, jTxtNomePessoal_GME, jTxtnumero_GME,
                jFmt_CEP_GME, jFmt_CNPJ_GME, jFmt_DataCadastro_GME, jFmt_Datanasc_GME, jFmt_telefone_loja_GME, jFmt_telefone_pessoal_GME,
                jCbxEstadoCivil_GME, jCbxGenero_GME, jBtnCancelar_GME,
                jBtnConfirmar_GME, jBtnPesquisar_GME
        );
        Util_GME.habilitar(true, jBtnAlterar_GME, jBtnIncluir_GME, jBtnExcluir_GME);
    }//GEN-LAST:event_jBtnPesquisar_GMEActionPerformed

    private void jBtnAlterar_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterar_GMEActionPerformed
        incluir = false;
        if (pesquisar == true) {
            Util_GME.habilitar(true, jTxtCargo_GME, jTxtCodigo_GME, jTxtEmailLoja_GME, jTxtEmail_pessoal_GME,
                    jTxtNomeLoja_GME, jTxtNomePessoal_GME, jTxtnumero_GME,
                    jFmt_CEP_GME, jFmt_CNPJ_GME, jFmt_DataCadastro_GME, jFmt_Datanasc_GME, jFmt_telefone_loja_GME, jFmt_telefone_pessoal_GME,
                    jCbxEstadoCivil_GME, jCbxGenero_GME, jBtnCancelar_GME, jBtnConfirmar_GME, jBtnExcluir_GME);
            Util_GME.habilitar(false, jTxtCodigo_GME, jBtnIncluir_GME, jBtnPesquisar_GME);
        } else {

            JOptionPane.showMessageDialog(this,
                    "Pesquise um Cliente antes",
                    "Erro em venda pesquisar",
                    JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jBtnAlterar_GMEActionPerformed

    private void jCbxGenero_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbxGenero_GMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbxGenero_GMEActionPerformed

    private void jBtnIncluir_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluir_GMEActionPerformed
        incluir = true;

        Util_GME.Limpar(jTxtCodigo_GME, jTxtCargo_GME, jTxtCodigo_GME, jTxtEmailLoja_GME, jTxtEmail_pessoal_GME,
                jTxtNomeLoja_GME, jTxtNomePessoal_GME,jCbxEstadoCivil_GME, jCbxGenero_GME, jTxtnumero_GME,
                jFmt_CEP_GME, jFmt_CNPJ_GME, jFmt_DataCadastro_GME, jFmt_Datanasc_GME, jFmt_telefone_loja_GME, jFmt_telefone_pessoal_GME);
        
        Util_GME.habilitar(true, jTxtCodigo_GME, jTxtCargo_GME, jTxtCodigo_GME, jTxtEmailLoja_GME, jTxtEmail_pessoal_GME,
                jTxtNomeLoja_GME, jTxtNomePessoal_GME, jTxtnumero_GME,
                jFmt_CEP_GME, jFmt_CNPJ_GME, jFmt_DataCadastro_GME, jFmt_Datanasc_GME, jFmt_telefone_loja_GME, jFmt_telefone_pessoal_GME,
                jCbxEstadoCivil_GME, jCbxGenero_GME,
                jBtnConfirmar_GME, jBtnCancelar_GME
        );
        Util_GME.habilitar(false, jBtnIncluir_GME, jBtnAlterar_GME, jBtnExcluir_GME, jBtnPesquisar_GME);
    }//GEN-LAST:event_jBtnIncluir_GMEActionPerformed

    private void jCbxEstadoCivil_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbxEstadoCivil_GMEActionPerformed

    }//GEN-LAST:event_jCbxEstadoCivil_GMEActionPerformed

    private void jTxtNomePessoal_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNomePessoal_GMEActionPerformed

    }//GEN-LAST:event_jTxtNomePessoal_GMEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgClientes_GME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgClientes_GME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgClientes_GME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgClientes_GME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgClientes_GME dialog = new JDlgClientes_GME(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CEP_GME;
    private javax.swing.JLabel CNPJ_GME;
    private javax.swing.JLabel Cargo_GME;
    private javax.swing.JLabel EmailLoja_GME;
    private javax.swing.JLabel Estado_civil_GME;
    private javax.swing.JLabel NomeLoja_GME;
    private javax.swing.JLabel TelefoneLoJa_GME;
    private javax.swing.JLabel codigo_GME;
    private javax.swing.JLabel data_de_Cadastro_GME;
    private javax.swing.JLabel data_de_nascimento_GME;
    private javax.swing.JLabel emailpessoal_GME;
    private javax.swing.JLabel genero_GME;
    private javax.swing.JButton jBtnAlterar_GME;
    private javax.swing.JButton jBtnCancelar_GME;
    private javax.swing.JButton jBtnConfirmar_GME;
    private javax.swing.JButton jBtnExcluir_GME;
    private javax.swing.JButton jBtnIncluir_GME;
    private javax.swing.JButton jBtnPesquisar_GME;
    private javax.swing.JComboBox<String> jCbxEstadoCivil_GME;
    private javax.swing.JComboBox<String> jCbxGenero_GME;
    private javax.swing.JFormattedTextField jFmt_CEP_GME;
    private javax.swing.JFormattedTextField jFmt_CNPJ_GME;
    private javax.swing.JFormattedTextField jFmt_DataCadastro_GME;
    private javax.swing.JFormattedTextField jFmt_Datanasc_GME;
    private javax.swing.JFormattedTextField jFmt_telefone_loja_GME;
    private javax.swing.JFormattedTextField jFmt_telefone_pessoal_GME;
    private javax.swing.JTextField jTxtCargo_GME;
    private javax.swing.JTextField jTxtCodigo_GME;
    private javax.swing.JTextField jTxtEmailLoja_GME;
    private javax.swing.JTextField jTxtEmail_pessoal_GME;
    private javax.swing.JTextField jTxtNomeLoja_GME;
    private javax.swing.JTextField jTxtNomePessoal_GME;
    private javax.swing.JTextField jTxtnumero_GME;
    private javax.swing.JLabel nomepessoal_GME;
    private javax.swing.JLabel numero_GME;
    private javax.swing.JLabel telefonePessoal_GME;
    // End of variables declaration//GEN-END:variables
}
