/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import bean.Empresas;
import bean.Clientes;
import bean.Venda;
import bean.VendaProduto;
import tools.Util_GME;
import dao.ClientesDAO;
import dao.EmpresasDAO;
import dao.UsuariosDAO;
import dao.VendaDAO;
import dao.VendaProdutoDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author guilh
 */
public class JDlgVendas_GME extends javax.swing.JDialog {

    ControllerVendaProdutos_GME controllerVendaProdutos_GME;

    /**
     * Creates new form JDlgVendas_GME
     */
    public JDlgVendas_GME(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Tela de Vendas");
        setLocationRelativeTo(null);

        jCbx_clientes_GME.removeAllItems();
        ClientesDAO clientesdao = new ClientesDAO();
        List listaCL = (List) clientesdao.listAll();
        for (Object object : listaCL) {
            jCbx_clientes_GME.addItem((Clientes) object);
        }
        jCbx_empresas_GME.removeAllItems();
        EmpresasDAO empresasDAO = new EmpresasDAO();
        List listaEM = (List) empresasDAO.listAll();
        for (Object object : listaEM) {
            jCbx_empresas_GME.addItem((Empresas) object);
        }

        Util_GME.habilitar(false, jTxt_code_GME, jCbx_clientes_GME, jCbx_empresas_GME, jBtn_cancelar_GME,
                jFmtData_GME, jTxt_valor_GME, jBtn_excluir_GME, jBtn_confirmar_GME,
                jBtn_side_adicionar_side, jBtn_side_alterar_GME, jBtn_side_delete_GME);
        controllerVendaProdutos_GME = new ControllerVendaProdutos_GME();
        controllerVendaProdutos_GME.setList(new ArrayList());
        jTbl_Colunas_GME.setModel(controllerVendaProdutos_GME);
    }

    private boolean incluir;
    private boolean pesquisar;

    public Venda viewBean() {
        Venda venda = new Venda();
        venda.setGmeIdVenda(Util_GME.strToInt(jTxt_code_GME.getText()));

        venda.setClientes((Clientes) jCbx_clientes_GME.getSelectedItem());
        venda.setEmpresas((Empresas) jCbx_empresas_GME.getSelectedItem());

        venda.setGmeData(Util_GME.strToDate(jFmtData_GME.getText()));
        venda.setGmeTotal(Util_GME.strToDouble(jTxt_valor_GME.getText()));

        return venda;
    }

    public void beanView(Venda venda) {

        jTxt_code_GME.setText(Util_GME.intToStr(venda.getGmeIdVenda()));
        jFmtData_GME.setText(Util_GME.dateToStr(venda.getGmeData()));
        jTxt_valor_GME.setText(Util_GME.doubleToStr(venda.getGmeTotal()));

        jCbx_clientes_GME.setSelectedItem(venda.getClientes());
        jCbx_empresas_GME.setSelectedItem(venda.getEmpresas());

        VendaProdutoDAO vendaProdutoDAO = new VendaProdutoDAO();
        List lista = (List) vendaProdutoDAO.listVenda(venda);
        controllerVendaProdutos_GME.setList(lista);
    }

    public JTable getjTbl_Colunas_GME() {
        return jTbl_Colunas_GME;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtn_side_delete_GME = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbl_Colunas_GME = new javax.swing.JTable();
        jLbl_code_GME = new javax.swing.JLabel();
        jLbl_Nome_clientes_GME = new javax.swing.JLabel();
        jBtn_incluir_GME = new javax.swing.JButton();
        jBtn_alterar_GME = new javax.swing.JButton();
        jLbl_valor_GME = new javax.swing.JLabel();
        jBtn_excluir_GME = new javax.swing.JButton();
        jLbl_data_GME = new javax.swing.JLabel();
        jBtn_confirmar_GME = new javax.swing.JButton();
        jTxt_code_GME = new javax.swing.JTextField();
        jBtn_cancelar_GME = new javax.swing.JButton();
        jBtn_Pesquisar_GME = new javax.swing.JButton();
        jBtn_side_adicionar_side = new javax.swing.JButton();
        jTxt_valor_GME = new javax.swing.JTextField();
        jBtn_side_alterar_GME = new javax.swing.JButton();
        jLbl_code_empresas_GME = new javax.swing.JLabel();
        jCbx_clientes_GME = new javax.swing.JComboBox<Clientes>();
        jCbx_empresas_GME = new javax.swing.JComboBox<Empresas>();
        jFmtData_GME = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBtn_side_delete_GME.setForeground(new java.awt.Color(255, 0, 0));
        jBtn_side_delete_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir_1.png"))); // NOI18N
        jBtn_side_delete_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_side_delete_GMEActionPerformed(evt);
            }
        });

        jTbl_Colunas_GME.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Coluna 1", "Coluna 2", "Coluna 3", "Coluna 4"
            }
        ));
        jScrollPane1.setViewportView(jTbl_Colunas_GME);

        jLbl_code_GME.setText("Código");

        jLbl_Nome_clientes_GME.setText("Nome de Clientes");

        jBtn_incluir_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtn_incluir_GME.setText("Incluir");
        jBtn_incluir_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_incluir_GMEActionPerformed(evt);
            }
        });

        jBtn_alterar_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar_1.png"))); // NOI18N
        jBtn_alterar_GME.setText("Alterar");
        jBtn_alterar_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_alterar_GMEActionPerformed(evt);
            }
        });

        jLbl_valor_GME.setText("Valor Total");

        jBtn_excluir_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir_1.png"))); // NOI18N
        jBtn_excluir_GME.setText("Excluir");
        jBtn_excluir_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_excluir_GMEActionPerformed(evt);
            }
        });

        jLbl_data_GME.setText("Data da Venda");

        jBtn_confirmar_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        jBtn_confirmar_GME.setText("Confirmar");
        jBtn_confirmar_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_confirmar_GMEActionPerformed(evt);
            }
        });

        jTxt_code_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_code_GMEActionPerformed(evt);
            }
        });

        jBtn_cancelar_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar_1.png"))); // NOI18N
        jBtn_cancelar_GME.setText("Cancelar");
        jBtn_cancelar_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_cancelar_GMEActionPerformed(evt);
            }
        });

        jBtn_Pesquisar_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar_1.png"))); // NOI18N
        jBtn_Pesquisar_GME.setText("Pesquisar");
        jBtn_Pesquisar_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_Pesquisar_GMEActionPerformed(evt);
            }
        });

        jBtn_side_adicionar_side.setForeground(new java.awt.Color(51, 153, 255));
        jBtn_side_adicionar_side.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir_1.png"))); // NOI18N
        jBtn_side_adicionar_side.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_side_adicionar_sideActionPerformed(evt);
            }
        });

        jTxt_valor_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_valor_GMEActionPerformed(evt);
            }
        });

        jBtn_side_alterar_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar_1.png"))); // NOI18N
        jBtn_side_alterar_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_side_alterar_GMEActionPerformed(evt);
            }
        });

        jLbl_code_empresas_GME.setText("Nome da Empresas");

        try {
            jFmtData_GME.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFmtData_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtData_GMEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtn_incluir_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_alterar_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_excluir_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_confirmar_GME)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_cancelar_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_Pesquisar_GME))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLbl_code_GME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxt_code_GME, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLbl_Nome_clientes_GME)
                            .addComponent(jCbx_clientes_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLbl_code_empresas_GME)
                            .addComponent(jCbx_empresas_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLbl_valor_GME, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxt_valor_GME, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFmtData_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbl_data_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBtn_side_delete_GME, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(jBtn_side_alterar_GME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtn_side_adicionar_side, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbl_code_GME)
                            .addComponent(jLbl_Nome_clientes_GME)
                            .addComponent(jLbl_code_empresas_GME))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxt_code_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCbx_clientes_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCbx_empresas_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbl_valor_GME)
                            .addComponent(jLbl_data_GME))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFmtData_GME, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxt_valor_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtn_side_adicionar_side, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtn_side_alterar_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtn_side_delete_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_incluir_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_alterar_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_excluir_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_confirmar_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_cancelar_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_Pesquisar_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jBtn_side_delete_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_side_delete_GMEActionPerformed
        if (jTbl_Colunas_GME.getSelectedRow() == -1) {
            Util_GME.messagem("Precisa selecionar uma linha!");
        } else {
            if (Util_GME.perguntar("Deseja excluir o produto ?") == true) {
                controllerVendaProdutos_GME.removeBean(jTbl_Colunas_GME.getSelectedRow());
                // ADICIONA AQUI
            }
        }
    }//GEN-LAST:event_jBtn_side_delete_GMEActionPerformed

    private void jBtn_incluir_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_incluir_GMEActionPerformed
        incluir = true;

        Util_GME.habilitar(true, jTxt_code_GME, jCbx_clientes_GME, jCbx_empresas_GME,
                jFmtData_GME, jTxt_valor_GME,
                jBtn_excluir_GME, jBtn_confirmar_GME, jBtn_cancelar_GME,
                jBtn_side_adicionar_side, jBtn_side_alterar_GME, jBtn_side_delete_GME
        );
        Util_GME.habilitar(false, jBtn_alterar_GME, jBtn_incluir_GME, jBtn_Pesquisar_GME);

        jTxt_code_GME.grabFocus();
    }//GEN-LAST:event_jBtn_incluir_GMEActionPerformed

    private void jBtn_alterar_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_alterar_GMEActionPerformed
        incluir = false;
        if (pesquisar == true) {
            Util_GME.habilitar(true, jTxt_code_GME, jCbx_clientes_GME, jCbx_empresas_GME,
                    jFmtData_GME, jTxt_valor_GME, jBtn_excluir_GME, jBtn_confirmar_GME,
                    jBtn_cancelar_GME, jBtn_side_adicionar_side, jBtn_side_alterar_GME, jBtn_side_delete_GME);
            Util_GME.habilitar(false, jBtn_alterar_GME, jBtn_incluir_GME, jBtn_Pesquisar_GME);

            jFmtData_GME.grabFocus();
        } else {

            JOptionPane.showMessageDialog(this,
                    "Pesquise um Venda antes",
                    "Erro em venda pesquisar",
                    JOptionPane.ERROR_MESSAGE);
            jBtn_incluir_GME.grabFocus();;
        }

    }//GEN-LAST:event_jBtn_alterar_GMEActionPerformed

    private void jBtn_excluir_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_excluir_GMEActionPerformed

        if (Util_GME.perguntar("Deseja Realizar a exclusão ?") == true) {
            VendaDAO vendaDAO = new VendaDAO();
            VendaProdutoDAO vendaProdutoDAO = new VendaProdutoDAO();
            for (int ind = 0; ind < jTbl_Colunas_GME.getRowCount(); ind++) {
                VendaProduto vendaProduto = controllerVendaProdutos_GME.getBean(ind);
                vendaProdutoDAO.delete(vendaProduto);
            }
            vendaDAO.delete(viewBean());
        }

        Util_GME.Limpar(jTxt_code_GME, jCbx_clientes_GME, jCbx_empresas_GME,
                jFmtData_GME, jTxt_valor_GME);

        Util_GME.habilitar(false, jTxt_code_GME, jCbx_clientes_GME, jCbx_empresas_GME,
                jFmtData_GME, jTxt_valor_GME,
                jBtn_alterar_GME, jBtn_excluir_GME, jBtn_confirmar_GME, jBtn_cancelar_GME,
                jBtn_side_adicionar_side, jBtn_side_delete_GME
        );
        Util_GME.habilitar(true, jBtn_side_alterar_GME, jBtn_incluir_GME, jBtn_Pesquisar_GME);

    }//GEN-LAST:event_jBtn_excluir_GMEActionPerformed

    private void jBtn_confirmar_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_confirmar_GMEActionPerformed
        pesquisar = false;
        VendaDAO vendaDAO = new VendaDAO();
        VendaProdutoDAO vendasProdutosDAO = new VendaProdutoDAO();
        Venda venda = viewBean();
        if (incluir == true) {
            vendaDAO.insert(venda);
            for (int ind = 0; ind < jTbl_Colunas_GME.getRowCount(); ind++) {
                VendaProduto vendaProduto = controllerVendaProdutos_GME.getBean(ind);
                vendaProduto.setVenda(venda);
                vendasProdutosDAO.insert(vendaProduto);
            }
        } else {
            vendaDAO.update(venda);

            vendasProdutosDAO.deleteProdutos(venda);

            for (int ind = 0; ind < jTbl_Colunas_GME.getRowCount(); ind++) {
                VendaProduto VendaProduto = controllerVendaProdutos_GME.getBean(ind);
                VendaProduto.setVenda(venda);
                vendasProdutosDAO.insert(VendaProduto);
            }
        }
        controllerVendaProdutos_GME.setList(new ArrayList<VendaProduto>());//code do chat para o limpar funcionar na Jtable

        Util_GME.Limpar(jTxt_code_GME, jCbx_clientes_GME, jCbx_empresas_GME,
                jFmtData_GME, jTxt_valor_GME, jTbl_Colunas_GME);

        Util_GME.habilitar(false, jTxt_code_GME, jCbx_clientes_GME, jCbx_empresas_GME,
                    jFmtData_GME, jTxt_valor_GME, jTbl_Colunas_GME, jBtn_excluir_GME, jBtn_confirmar_GME,
                    jBtn_side_alterar_GME, jBtn_cancelar_GME, jBtn_side_adicionar_side, jBtn_side_delete_GME
            );
            Util_GME.habilitar(true, jBtn_incluir_GME, jBtn_Pesquisar_GME);
    }//GEN-LAST:event_jBtn_confirmar_GMEActionPerformed

    private void jTxt_code_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_code_GMEActionPerformed

    }//GEN-LAST:event_jTxt_code_GMEActionPerformed

    private void jBtn_cancelar_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_cancelar_GMEActionPerformed
        pesquisar = false;

        if (Util_GME.perguntar("Deseja cancelar esse registro de Venda?") == true) {

            controllerVendaProdutos_GME.setList(new ArrayList<VendaProduto>());//code do chat para o limpar funcionar na Jtable

            Util_GME.Limpar(jTxt_code_GME, jCbx_clientes_GME, jCbx_empresas_GME,
                    jFmtData_GME, jTxt_valor_GME, jTbl_Colunas_GME);

            Util_GME.habilitar(false, jTxt_code_GME, jCbx_clientes_GME, jCbx_empresas_GME,
                    jFmtData_GME, jTxt_valor_GME, jTbl_Colunas_GME, jBtn_excluir_GME, jBtn_confirmar_GME,
                    jBtn_side_alterar_GME, jBtn_cancelar_GME, jBtn_side_adicionar_side, jBtn_side_delete_GME
            );
            Util_GME.habilitar(true, jBtn_incluir_GME, jBtn_Pesquisar_GME);
        }

    }//GEN-LAST:event_jBtn_cancelar_GMEActionPerformed

    private void jBtn_Pesquisar_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_Pesquisar_GMEActionPerformed
        pesquisar = false;

        JDlgVendasPesquisar_GME jDlgVendasPesquisar_GME = new JDlgVendasPesquisar_GME(null, true);
        jDlgVendasPesquisar_GME.setTelaAnterior(this);
        jDlgVendasPesquisar_GME.setVisible(true);

        Util_GME.habilitar(false, jTxt_code_GME, jCbx_clientes_GME, jCbx_empresas_GME,
                jFmtData_GME, jTxt_valor_GME, jBtn_side_delete_GME, jBtn_incluir_GME, jBtn_Pesquisar_GME,
                jBtn_side_adicionar_side, jBtn_side_alterar_GME, jTbl_Colunas_GME
        );
        Util_GME.habilitar(true, jBtn_alterar_GME, jBtn_excluir_GME, jBtn_confirmar_GME, jBtn_cancelar_GME);
    }//GEN-LAST:event_jBtn_Pesquisar_GMEActionPerformed

    private void jBtn_side_adicionar_sideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_side_adicionar_sideActionPerformed
        JDlgVendas_produtos_GME jDlgVendas_produtos_GME = new JDlgVendas_produtos_GME(null, true);
        jDlgVendas_produtos_GME.setTelaAnterior(this, null);
        jDlgVendas_produtos_GME.setVisible(true);
    }//GEN-LAST:event_jBtn_side_adicionar_sideActionPerformed

    private void jTxt_valor_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_valor_GMEActionPerformed

    }//GEN-LAST:event_jTxt_valor_GMEActionPerformed

    private void jBtn_side_alterar_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_side_alterar_GMEActionPerformed
        if (jTbl_Colunas_GME.getSelectedRow() == -1) {
            Util_GME.messagem("É preciso selecionar uma linha");
        }
        JDlgVendas_produtos_GME Vendas_produtos_GME = new JDlgVendas_produtos_GME(null, true);
        VendaProduto vendaProduto = controllerVendaProdutos_GME.getBean(jTbl_Colunas_GME.getSelectedRow());
        Vendas_produtos_GME.setTelaAnterior(this, vendaProduto);
        Vendas_produtos_GME.setVisible(true);
    }//GEN-LAST:event_jBtn_side_alterar_GMEActionPerformed

    private void jFmtData_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtData_GMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtData_GMEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas_GME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas_GME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas_GME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas_GME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgVendas_GME dialog = new JDlgVendas_GME(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_Pesquisar_GME;
    private javax.swing.JButton jBtn_alterar_GME;
    private javax.swing.JButton jBtn_cancelar_GME;
    private javax.swing.JButton jBtn_confirmar_GME;
    private javax.swing.JButton jBtn_excluir_GME;
    private javax.swing.JButton jBtn_incluir_GME;
    private javax.swing.JButton jBtn_side_adicionar_side;
    private javax.swing.JButton jBtn_side_alterar_GME;
    private javax.swing.JButton jBtn_side_delete_GME;
    private javax.swing.JComboBox<Clientes> jCbx_clientes_GME;
    private javax.swing.JComboBox<Empresas> jCbx_empresas_GME;
    private javax.swing.JFormattedTextField jFmtData_GME;
    private javax.swing.JLabel jLbl_Nome_clientes_GME;
    private javax.swing.JLabel jLbl_code_GME;
    private javax.swing.JLabel jLbl_code_empresas_GME;
    private javax.swing.JLabel jLbl_data_GME;
    private javax.swing.JLabel jLbl_valor_GME;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTbl_Colunas_GME;
    private javax.swing.JTextField jTxt_code_GME;
    private javax.swing.JTextField jTxt_valor_GME;
    // End of variables declaration//GEN-END:variables

}
