/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.VendaProduto;
import bean.Produtos;
import dao.ProdutosDAO;
import java.util.List;
import tools.Util_GME;

/**
 *
 * @author u07880060103
 */
public class JDlgVendas_produtos_GME extends javax.swing.JDialog {
    JDlgVendas_GME jDlgVenda;
    boolean incluir;
    /**
     * Creates new form JDlgVendaProduto
     */
    public JDlgVendas_produtos_GME(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Pedidos Produtos");
        Util_GME.habilitar(false, jTxtValorUnitario_GME, jTxtTotal_GME);
        jTxtQuantidade_GME.setText("1");
        ProdutosDAO veiculosDAO = new ProdutosDAO();
        List lista = (List) veiculosDAO.listAll();
        for (Object object : lista) {
            jCboProduto_GME.addItem((Produtos) object);
        }   
    }
    
    public void setTelaAnterior(JDlgVendas_GME jDlgVenda, VendaProduto vendaProduto) {
        this.jDlgVenda = jDlgVenda;
           if (vendaProduto != null) {
            incluir = false;
            jCboProduto_GME.setSelectedItem(vendaProduto.getProdutos());
            jTxtQuantidade_GME.setText(Util_GME.intToStr(vendaProduto.getGmeQuantidade()));
        } else {
            incluir = true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLbl_produto_GME = new javax.swing.JLabel();
        jCboProduto_GME = new javax.swing.JComboBox<Produtos>();
        jLbl_quant_GME = new javax.swing.JLabel();
        jTxtQuantidade_GME = new javax.swing.JTextField();
        jLbl_valorUni_GME = new javax.swing.JLabel();
        jTxtValorUnitario_GME = new javax.swing.JTextField();
        jLbl_Total_GME = new javax.swing.JLabel();
        jTxtTotal_GME = new javax.swing.JTextField();
        jBtnOk_GME = new javax.swing.JButton();
        jBtnSair_GME = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLbl_produto_GME.setText("Produto");

        jCboProduto_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboProduto_GMEActionPerformed(evt);
            }
        });

        jLbl_quant_GME.setText("Quantidade");

        jTxtQuantidade_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtQuantidade_GMEActionPerformed(evt);
            }
        });
        jTxtQuantidade_GME.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtQuantidade_GMEKeyReleased(evt);
            }
        });

        jLbl_valorUni_GME.setText("Valor Unitário");

        jLbl_Total_GME.setText("Valor Total");

        jTxtTotal_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtTotal_GMEActionPerformed(evt);
            }
        });

        jBtnOk_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        jBtnOk_GME.setText("Ok");
        jBtnOk_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOk_GMEActionPerformed(evt);
            }
        });

        jBtnSair_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit.png"))); // NOI18N
        jBtnSair_GME.setText("Sair");
        jBtnSair_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSair_GMEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLbl_produto_GME)
                            .addComponent(jLbl_quant_GME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxtQuantidade_GME))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLbl_valorUni_GME, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(jTxtValorUnitario_GME))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLbl_Total_GME)
                                .addGap(30, 30, 30))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxtTotal_GME)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCboProduto_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnSair_GME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnOk_GME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLbl_produto_GME)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCboProduto_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBtnOk_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLbl_Total_GME)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLbl_quant_GME)
                                .addComponent(jLbl_valorUni_GME)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtQuantidade_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtValorUnitario_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtTotal_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnSair_GME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtQuantidade_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtQuantidade_GMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtQuantidade_GMEActionPerformed

    private void jTxtTotal_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtTotal_GMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtTotal_GMEActionPerformed

    private void jBtnOk_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOk_GMEActionPerformed
        // TODO add your handling code here:
      VendaProduto vendaProduto = new VendaProduto();
        vendaProduto.setProdutos((Produtos) jCboProduto_GME.getSelectedItem());
        vendaProduto.setGmeQuantidade(Util_GME.strToInt(jTxtQuantidade_GME.getText()));
        vendaProduto.setGmeValorUnitario(Util_GME.strToDouble(jTxtValorUnitario_GME.getText()));
        if (incluir == true) {
            jDlgVenda.controllerVendaProdutos_GME.addBean(vendaProduto);
        } else {
            jDlgVenda.controllerVendaProdutos_GME.removeBean(jDlgVenda.getjTbl_Colunas_GME().getSelectedRow());
            jDlgVenda.controllerVendaProdutos_GME.addBean(vendaProduto);
        }
        setVisible(false);
    }//GEN-LAST:event_jBtnOk_GMEActionPerformed

    private void jBtnSair_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSair_GMEActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jBtnSair_GMEActionPerformed

    private void jCboProduto_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboProduto_GMEActionPerformed
        // TODO add your handling code here:
        Produtos produtos = (Produtos) jCboProduto_GME.getSelectedItem();
        jTxtValorUnitario_GME.setText(Util_GME.doubleToStr(produtos.getGmeValorUnitario()));
        int quant = Util_GME.strToInt(jTxtQuantidade_GME.getText());
        jTxtTotal_GME.setText(Util_GME.doubleToStr(quant * produtos.getGmeValorUnitario()));        
    }//GEN-LAST:event_jCboProduto_GMEActionPerformed

    private void jTxtQuantidade_GMEKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtQuantidade_GMEKeyReleased
        // TODO add your handling code here:
        if (jTxtQuantidade_GME.getText().isEmpty()== false) {
            Produtos produtos = (Produtos) jCboProduto_GME.getSelectedItem();        
            int quant = Util_GME.strToInt(jTxtQuantidade_GME.getText());
            jTxtTotal_GME.setText(Util_GME.doubleToStr(quant * produtos.getGmeValorUnitario()));                
        } else {
            jTxtTotal_GME.setText("");
        }
    }//GEN-LAST:event_jTxtQuantidade_GMEKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas_produtos_GME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas_produtos_GME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas_produtos_GME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas_produtos_GME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgVendas_produtos_GME dialog = new JDlgVendas_produtos_GME(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnOk_GME;
    private javax.swing.JButton jBtnSair_GME;
    private javax.swing.JComboBox<Produtos> jCboProduto_GME;
    private javax.swing.JLabel jLbl_Total_GME;
    private javax.swing.JLabel jLbl_produto_GME;
    private javax.swing.JLabel jLbl_quant_GME;
    private javax.swing.JLabel jLbl_valorUni_GME;
    private javax.swing.JTextField jTxtQuantidade_GME;
    private javax.swing.JTextField jTxtTotal_GME;
    private javax.swing.JTextField jTxtValorUnitario_GME;
    // End of variables declaration//GEN-END:variables
}
