/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

/**
 *
 * @author guilh
 */
public class JDlgEmpresas_GME extends javax.swing.JDialog {

    /**
     * Creates new form jDlgEmpresas_GME
     */
    public JDlgEmpresas_GME(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Tela de Cadastro de Empresas");
        setLocationRelativeTo(null);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtCodigo_GME = new javax.swing.JTextField();
        GME_jBtnAlterar = new javax.swing.JButton();
        numero_GME = new javax.swing.JLabel();
        GME_jBtnIncluir = new javax.swing.JButton();
        jTxtnumero_GME = new javax.swing.JTextField();
        nome_GME = new javax.swing.JLabel();
        CNPJ_GME = new javax.swing.JLabel();
        jTxtNomeEMPRE_GME = new javax.swing.JTextField();
        jFmt_CEP_GME = new javax.swing.JFormattedTextField();
        CEP_GME = new javax.swing.JLabel();
        jFmt_TEL_EMPRE_GME = new javax.swing.JFormattedTextField();
        Telefone_GME = new javax.swing.JLabel();
        jFmt_cnpj_GME = new javax.swing.JFormattedTextField();
        TelefonePessoal_GME = new javax.swing.JLabel();
        jFmt_TEL_REP_GME = new javax.swing.JFormattedTextField();
        GME_jBtnConfirmar = new javax.swing.JButton();
        jTxtNomeREP_GME = new javax.swing.JTextField();
        GME_jBtnExcluir = new javax.swing.JButton();
        Cargo_GME = new javax.swing.JLabel();
        GME_jBtnCancelar = new javax.swing.JButton();
        codigo_GME = new javax.swing.JLabel();
        GME_jBtnPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        GME_jBtnAlterar.setText("Alterar");
        GME_jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GME_jBtnAlterarActionPerformed(evt);
            }
        });

        numero_GME.setText("Número [LOC]");

        GME_jBtnIncluir.setText("Incluir");
        GME_jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GME_jBtnIncluirActionPerformed(evt);
            }
        });

        nome_GME.setText("Nome da empresa");

        CNPJ_GME.setText("CNPJ ");

        try {
            jFmt_CEP_GME.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        CEP_GME.setText("CEP");

        try {
            jFmt_TEL_EMPRE_GME.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##).#.####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        Telefone_GME.setText("Telefone da empresa");

        try {
            jFmt_cnpj_GME.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        TelefonePessoal_GME.setText("nome do representante");

        try {
            jFmt_TEL_REP_GME.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##).#.####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        GME_jBtnConfirmar.setText("Confirmar");
        GME_jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GME_jBtnConfirmarActionPerformed(evt);
            }
        });

        jTxtNomeREP_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNomeREP_GMEActionPerformed(evt);
            }
        });

        GME_jBtnExcluir.setText("Excluir");
        GME_jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GME_jBtnExcluirActionPerformed(evt);
            }
        });

        Cargo_GME.setText("Telefone do Representante");

        GME_jBtnCancelar.setText("Cancelar");
        GME_jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GME_jBtnCancelarActionPerformed(evt);
            }
        });

        codigo_GME.setText("Codigo [ID]");

        GME_jBtnPesquisar.setText("Pesquisar");
        GME_jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GME_jBtnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GME_jBtnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTxtNomeEMPRE_GME)
                                        .addComponent(nome_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jFmt_CEP_GME, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(CEP_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFmt_TEL_EMPRE_GME)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(GME_jBtnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Telefone_GME)
                                            .addComponent(CNPJ_GME))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jFmt_cnpj_GME)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxtnumero_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(GME_jBtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(GME_jBtnConfirmar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GME_jBtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GME_jBtnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Cargo_GME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTxtNomeREP_GME)
                                        .addComponent(TelefonePessoal_GME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jFmt_TEL_REP_GME))
                                    .addComponent(jTxtCodigo_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(codigo_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numero_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TelefonePessoal_GME)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtNomeREP_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Cargo_GME)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFmt_TEL_REP_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(codigo_GME)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCodigo_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nome_GME)
                            .addComponent(Telefone_GME))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtNomeEMPRE_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmt_TEL_EMPRE_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CEP_GME)
                            .addComponent(CNPJ_GME))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFmt_CEP_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmt_cnpj_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numero_GME)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtnumero_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GME_jBtnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GME_jBtnExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GME_jBtnConfirmar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(GME_jBtnIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GME_jBtnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GME_jBtnPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GME_jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GME_jBtnAlterarActionPerformed

    }//GEN-LAST:event_GME_jBtnAlterarActionPerformed

    private void GME_jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GME_jBtnIncluirActionPerformed
   
    }//GEN-LAST:event_GME_jBtnIncluirActionPerformed

    private void GME_jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GME_jBtnConfirmarActionPerformed
    
    }//GEN-LAST:event_GME_jBtnConfirmarActionPerformed

    private void jTxtNomeREP_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNomeREP_GMEActionPerformed

    }//GEN-LAST:event_jTxtNomeREP_GMEActionPerformed

    private void GME_jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GME_jBtnExcluirActionPerformed

    }//GEN-LAST:event_GME_jBtnExcluirActionPerformed

    private void GME_jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GME_jBtnCancelarActionPerformed

    }//GEN-LAST:event_GME_jBtnCancelarActionPerformed

    private void GME_jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GME_jBtnPesquisarActionPerformed
        JDlgEmpresasPesquisar_GME jDlgEmpresasPesquisar_GME = new JDlgEmpresasPesquisar_GME(null,true);
         jDlgEmpresasPesquisar_GME.setVisible(true);
    }//GEN-LAST:event_GME_jBtnPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgEmpresas_GME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgEmpresas_GME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgEmpresas_GME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgEmpresas_GME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgEmpresas_GME dialog = new JDlgEmpresas_GME(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CEP_GME;
    private javax.swing.JLabel CNPJ_GME;
    private javax.swing.JLabel Cargo_GME;
    private javax.swing.JButton GME_jBtnAlterar;
    private javax.swing.JButton GME_jBtnCancelar;
    private javax.swing.JButton GME_jBtnConfirmar;
    private javax.swing.JButton GME_jBtnExcluir;
    private javax.swing.JButton GME_jBtnIncluir;
    private javax.swing.JButton GME_jBtnPesquisar;
    private javax.swing.JLabel TelefonePessoal_GME;
    private javax.swing.JLabel Telefone_GME;
    private javax.swing.JLabel codigo_GME;
    private javax.swing.JFormattedTextField jFmt_CEP_GME;
    private javax.swing.JFormattedTextField jFmt_TEL_EMPRE_GME;
    private javax.swing.JFormattedTextField jFmt_TEL_REP_GME;
    private javax.swing.JFormattedTextField jFmt_cnpj_GME;
    private javax.swing.JTextField jTxtCodigo_GME;
    private javax.swing.JTextField jTxtNomeEMPRE_GME;
    private javax.swing.JTextField jTxtNomeREP_GME;
    private javax.swing.JTextField jTxtnumero_GME;
    private javax.swing.JLabel nome_GME;
    private javax.swing.JLabel numero_GME;
    // End of variables declaration//GEN-END:variables
}
