/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import tools.Util_GME;

/**
 *
 * @author u07273579130
 */
public class JDlgVendas_produtos_GME extends javax.swing.JDialog {

    /**
     * Creates new form JDlgVendas_produtos_GME
     */
    public JDlgVendas_produtos_GME(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Tela de Vendas Produtos");
        setLocationRelativeTo(null);
        Util_GME.habilitar(false, jTxt_code_GME,jTxt_ValorUnitario_GME,jTxt_code_Venda_GME,jTxt_code_produto_GME,jTxt_quantidade_GME,
                
                jBtn_alterar_GME,jBtn_excluir_GME,jBtn_confirmar_GME,jBtn_cancelar_GME,
                
                jBtn_side_adicionar_side,jBtn_side_alterar_GME,jBtn_side_delete_GME
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtn_alterar_GME = new javax.swing.JButton();
        jTxt_quantidade_GME = new javax.swing.JTextField();
        jLbl_Quantidade_GME = new javax.swing.JLabel();
        jBtn_side_alterar_GME = new javax.swing.JButton();
        jBtn_excluir_GME = new javax.swing.JButton();
        jTxt_ValorUnitario_GME = new javax.swing.JTextField();
        jLbl_ValorUnitario_GME = new javax.swing.JLabel();
        jBtn_side_delete_GME = new javax.swing.JButton();
        jBtn_confirmar_GME = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbl_Colunas_GME = new javax.swing.JTable();
        jTxt_code_GME = new javax.swing.JTextField();
        jBtn_cancelar_GME = new javax.swing.JButton();
        jLbl_code_GME = new javax.swing.JLabel();
        jTxt_code_Venda_GME = new javax.swing.JTextField();
        jLbl_code_Venda_GME = new javax.swing.JLabel();
        jBtn_Pesquisar_GME = new javax.swing.JButton();
        jBtn_incluir_GME = new javax.swing.JButton();
        jTxt_code_produto_GME = new javax.swing.JTextField();
        jLbl_code_produto_GME = new javax.swing.JLabel();
        jBtn_side_adicionar_side = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBtn_alterar_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar_1.png"))); // NOI18N
        jBtn_alterar_GME.setText("Alterar");
        jBtn_alterar_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_alterar_GMEActionPerformed(evt);
            }
        });

        jTxt_quantidade_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_quantidade_GMEActionPerformed(evt);
            }
        });

        jLbl_Quantidade_GME.setText("Valor Quantidade");

        jBtn_side_alterar_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar_1.png"))); // NOI18N
        jBtn_side_alterar_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_side_alterar_GMEActionPerformed(evt);
            }
        });

        jBtn_excluir_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir_1.png"))); // NOI18N
        jBtn_excluir_GME.setText("Excluir");
        jBtn_excluir_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_excluir_GMEActionPerformed(evt);
            }
        });

        jTxt_ValorUnitario_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_ValorUnitario_GMEActionPerformed(evt);
            }
        });

        jLbl_ValorUnitario_GME.setText("Valor Unitario");

        jBtn_side_delete_GME.setForeground(new java.awt.Color(255, 0, 0));
        jBtn_side_delete_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir_1.png"))); // NOI18N
        jBtn_side_delete_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_side_delete_GMEActionPerformed(evt);
            }
        });

        jBtn_confirmar_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        jBtn_confirmar_GME.setText("Confirmar");
        jBtn_confirmar_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_confirmar_GMEActionPerformed(evt);
            }
        });

        jTbl_Colunas_GME.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Coluna 1", "Coluna 2", "Coluna 3", "Coluna 4"
            }
        ));
        jScrollPane1.setViewportView(jTbl_Colunas_GME);

        jTxt_code_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_code_GMEActionPerformed(evt);
            }
        });

        jBtn_cancelar_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar_1.png"))); // NOI18N
        jBtn_cancelar_GME.setText("Cancelar");
        jBtn_cancelar_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_cancelar_GMEActionPerformed(evt);
            }
        });

        jLbl_code_GME.setText("Código");

        jTxt_code_Venda_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_code_Venda_GMEActionPerformed(evt);
            }
        });

        jLbl_code_Venda_GME.setText("Código Venda");

        jBtn_Pesquisar_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar_1.png"))); // NOI18N
        jBtn_Pesquisar_GME.setText("Pesquisar");
        jBtn_Pesquisar_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_Pesquisar_GMEActionPerformed(evt);
            }
        });

        jBtn_incluir_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtn_incluir_GME.setText("Incluir");
        jBtn_incluir_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_incluir_GMEActionPerformed(evt);
            }
        });

        jTxt_code_produto_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_code_produto_GMEActionPerformed(evt);
            }
        });

        jLbl_code_produto_GME.setText("Código Produto");

        jBtn_side_adicionar_side.setForeground(new java.awt.Color(51, 153, 255));
        jBtn_side_adicionar_side.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir_1.png"))); // NOI18N
        jBtn_side_adicionar_side.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_side_adicionar_sideActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLbl_code_GME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxt_code_GME, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxt_code_Venda_GME)
                            .addComponent(jLbl_code_Venda_GME, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLbl_code_produto_GME)
                            .addComponent(jTxt_code_produto_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxt_quantidade_GME)
                            .addComponent(jLbl_Quantidade_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxt_ValorUnitario_GME)
                            .addComponent(jLbl_ValorUnitario_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtn_incluir_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn_alterar_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn_excluir_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn_confirmar_GME)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn_cancelar_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn_Pesquisar_GME))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jBtn_side_delete_GME, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                    .addComponent(jBtn_side_alterar_GME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBtn_side_adicionar_side, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbl_code_GME)
                            .addComponent(jLbl_code_produto_GME)
                            .addComponent(jLbl_code_Venda_GME))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxt_code_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxt_code_Venda_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxt_code_produto_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLbl_Quantidade_GME, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLbl_ValorUnitario_GME, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxt_quantidade_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxt_ValorUnitario_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jBtn_side_adicionar_side, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtn_side_alterar_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtn_side_delete_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_incluir_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_alterar_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_excluir_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_confirmar_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_cancelar_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_Pesquisar_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_alterar_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_alterar_GMEActionPerformed

    }//GEN-LAST:event_jBtn_alterar_GMEActionPerformed

    private void jTxt_quantidade_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_quantidade_GMEActionPerformed

    }//GEN-LAST:event_jTxt_quantidade_GMEActionPerformed

    private void jBtn_side_alterar_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_side_alterar_GMEActionPerformed

    }//GEN-LAST:event_jBtn_side_alterar_GMEActionPerformed

    private void jBtn_excluir_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_excluir_GMEActionPerformed
        if(Util_GME.perguntar("Deseja excluir esse registro de Venda Produto?") == true){
            Util_GME.habilitar(false, jTxt_code_GME,jTxt_ValorUnitario_GME,jTxt_code_Venda_GME,jTxt_code_produto_GME,jTxt_quantidade_GME,
                
                jBtn_alterar_GME,jBtn_excluir_GME,jBtn_confirmar_GME,jBtn_cancelar_GME,
                
                jBtn_side_adicionar_side,jBtn_side_alterar_GME,jBtn_side_delete_GME
            );
            Util_GME.habilitar(true, jBtn_incluir_GME,jBtn_Pesquisar_GME);
        }
    }//GEN-LAST:event_jBtn_excluir_GMEActionPerformed

    private void jTxt_ValorUnitario_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_ValorUnitario_GMEActionPerformed

    }//GEN-LAST:event_jTxt_ValorUnitario_GMEActionPerformed

    private void jBtn_side_delete_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_side_delete_GMEActionPerformed
        if(Util_GME.perguntar("Deseja DELETAR esse registro de Venda Produto?") == true){
        }
    }//GEN-LAST:event_jBtn_side_delete_GMEActionPerformed

    private void jBtn_confirmar_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_confirmar_GMEActionPerformed
        Util_GME.habilitar(false, jTxt_code_GME,jTxt_ValorUnitario_GME,jTxt_code_Venda_GME,jTxt_code_produto_GME,jTxt_quantidade_GME,
                
        jBtn_alterar_GME,jBtn_excluir_GME,jBtn_confirmar_GME,jBtn_cancelar_GME,
                
        jBtn_side_adicionar_side,jBtn_side_alterar_GME,jBtn_side_delete_GME
        );
        Util_GME.habilitar(true, jBtn_incluir_GME,jBtn_Pesquisar_GME);

    }//GEN-LAST:event_jBtn_confirmar_GMEActionPerformed

    private void jTxt_code_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_code_GMEActionPerformed

    }//GEN-LAST:event_jTxt_code_GMEActionPerformed

    private void jBtn_cancelar_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_cancelar_GMEActionPerformed
        if(Util_GME.perguntar("Deseja cancelar esse registro de Venda Produto?") == true){
            Util_GME.habilitar(false, jTxt_code_GME,jTxt_ValorUnitario_GME,jTxt_code_Venda_GME,jTxt_code_produto_GME,jTxt_quantidade_GME,
                
                jBtn_alterar_GME,jBtn_excluir_GME,jBtn_confirmar_GME,jBtn_cancelar_GME,
                
                jBtn_side_adicionar_side,jBtn_side_alterar_GME,jBtn_side_delete_GME
            );
            Util_GME.habilitar(true, jBtn_incluir_GME,jBtn_Pesquisar_GME);
        }
    }//GEN-LAST:event_jBtn_cancelar_GMEActionPerformed

    private void jTxt_code_Venda_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_code_Venda_GMEActionPerformed

    }//GEN-LAST:event_jTxt_code_Venda_GMEActionPerformed

    private void jBtn_Pesquisar_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_Pesquisar_GMEActionPerformed
        JDlgVendas_produtosPesquisar_GME jDlgVendas_produtosPesquisar_GME = new JDlgVendas_produtosPesquisar_GME(null,true);
        jDlgVendas_produtosPesquisar_GME.setVisible(true);
    }//GEN-LAST:event_jBtn_Pesquisar_GMEActionPerformed

    private void jBtn_incluir_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_incluir_GMEActionPerformed
        Util_GME.habilitar(true, jTxt_code_GME,jTxt_ValorUnitario_GME,jTxt_code_Venda_GME,jTxt_code_produto_GME,jTxt_quantidade_GME,
                
                jBtn_alterar_GME,jBtn_excluir_GME,jBtn_confirmar_GME,jBtn_cancelar_GME,
                
                jBtn_side_adicionar_side,jBtn_side_alterar_GME,jBtn_side_delete_GME
        );
        Util_GME.habilitar(false, jBtn_incluir_GME,jBtn_Pesquisar_GME);
    }//GEN-LAST:event_jBtn_incluir_GMEActionPerformed

    private void jTxt_code_produto_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_code_produto_GMEActionPerformed

    }//GEN-LAST:event_jTxt_code_produto_GMEActionPerformed

    private void jBtn_side_adicionar_sideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_side_adicionar_sideActionPerformed

    }//GEN-LAST:event_jBtn_side_adicionar_sideActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas_produtos_GME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas_produtos_GME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas_produtos_GME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas_produtos_GME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgVendas_produtos_GME dialog = new JDlgVendas_produtos_GME(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_Pesquisar_GME;
    private javax.swing.JButton jBtn_alterar_GME;
    private javax.swing.JButton jBtn_cancelar_GME;
    private javax.swing.JButton jBtn_confirmar_GME;
    private javax.swing.JButton jBtn_excluir_GME;
    private javax.swing.JButton jBtn_incluir_GME;
    private javax.swing.JButton jBtn_side_adicionar_side;
    private javax.swing.JButton jBtn_side_alterar_GME;
    private javax.swing.JButton jBtn_side_delete_GME;
    private javax.swing.JLabel jLbl_Quantidade_GME;
    private javax.swing.JLabel jLbl_ValorUnitario_GME;
    private javax.swing.JLabel jLbl_code_GME;
    private javax.swing.JLabel jLbl_code_Venda_GME;
    private javax.swing.JLabel jLbl_code_produto_GME;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTbl_Colunas_GME;
    private javax.swing.JTextField jTxt_ValorUnitario_GME;
    private javax.swing.JTextField jTxt_code_GME;
    private javax.swing.JTextField jTxt_code_Venda_GME;
    private javax.swing.JTextField jTxt_code_produto_GME;
    private javax.swing.JTextField jTxt_quantidade_GME;
    // End of variables declaration//GEN-END:variables
}
