/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.Usuarios;
import dao.UsuariosDAO;
import tools.Util_GME;

/**
 *
 * @author guilh
 */
public class JDlgUsuarios_GME extends javax.swing.JDialog {

    public JDlgUsuarios_GME(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Tela de Cadastro de Usuários");
        setLocationRelativeTo(null);

        Util_GME.habilitar(false, jTxtCodigo_GME, jTxtNome_GME, jTxtApelido_GME, jFmtCpf_GME,
                jFmtDataDeNascimento_GME, jCboNivel_GME, jChbAtivo_GME, jPwfSenha_GME,
                jBtnAlterar_GME, jBtnConfirmar_GME, jBtnExcluir_GME, jBtnCancelar_GME
        );

    }

    private boolean incluir;
    
    public Usuarios viewBean(){
    Usuarios usuarios = new Usuarios();
    int codigo = Util_GME.strToInt(jTxtCodigo_GME.getText());
    usuarios.setGmeIdUsuarios(codigo);
    
    usuarios.setGmeApelido(jTxtApelido_GME.getText());
    usuarios.setGmeCpf(jFmtCpf_GME.getText());
    usuarios.setGmeNome(jTxtNome_GME.getText());
    usuarios.setGmeDatanasc(Util_GME.strToDate(jFmtDataDeNascimento_GME.getText()));
    usuarios.setGmeSenha(jPwfSenha_GME.getText());
    usuarios.setGmeNivel(jCboNivel_GME.getSelectedIndex());
    if(jChbAtivo_GME.isSelected()== true){
       usuarios.setGmeAtivo(Util_GME.strToChar("S"));
       }else{
       usuarios.setGmeAtivo(Util_GME.strToChar("N"));
       }
    
    return usuarios;
    }
    
    public void beanView(Usuarios usuarios){
        jTxtCodigo_GME.setText(Util_GME.intToStr(usuarios.getGmeIdUsuarios()));
        jTxtNome_GME.setText(usuarios.getGmeNome());
        jTxtApelido_GME.setText(usuarios.getGmeApelido());
        jFmtCpf_GME.setText(usuarios.getGmeSenha());
        jFmtDataDeNascimento_GME.setText(Util_GME.dateToStr(usuarios.getGmeDatanasc()));
        jPwfSenha_GME.setText(usuarios.getGmeSenha());
        jCboNivel_GME.setSelectedIndex(usuarios.getGmeNivel());
        if (usuarios.getGmeAtivo() =='S'){
        jChbAtivo_GME.setSelected(true);
        }else{
        jChbAtivo_GME.setSelected(false);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLbl_codigo_GME = new javax.swing.JLabel();
        jTxtCodigo_GME = new javax.swing.JTextField();
        jLbl_nome_GME = new javax.swing.JLabel();
        jTxtNome_GME = new javax.swing.JTextField();
        jLbl_apelido_GME = new javax.swing.JLabel();
        jTxtApelido_GME = new javax.swing.JTextField();
        jLbl_cpf_GME = new javax.swing.JLabel();
        jFmtCpf_GME = new javax.swing.JFormattedTextField();
        jLbl_date_GME = new javax.swing.JLabel();
        jFmtDataDeNascimento_GME = new javax.swing.JFormattedTextField();
        jLbl_senha_GME = new javax.swing.JLabel();
        jPwfSenha_GME = new javax.swing.JPasswordField();
        jLbl_nivel_GME = new javax.swing.JLabel();
        jChbAtivo_GME = new javax.swing.JCheckBox();
        jCboNivel_GME = new javax.swing.JComboBox<>();
        jLbl_ativo_GME = new javax.swing.JLabel();
        jBtnIncluir_GME = new javax.swing.JButton();
        jBtnAlterar_GME = new javax.swing.JButton();
        jBtnExcluir_GME = new javax.swing.JButton();
        jBtnConfirmar_GME = new javax.swing.JButton();
        jBtnCancelar_GME = new javax.swing.JButton();
        jBtnPesquisar_GME = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLbl_codigo_GME.setText("Código");

        jTxtCodigo_GME.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtCodigo_GMEFocusLost(evt);
            }
        });

        jLbl_nome_GME.setText("Nome");

        jTxtNome_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNome_GMEActionPerformed(evt);
            }
        });

        jLbl_apelido_GME.setText("Apelido");

        jLbl_cpf_GME.setText("CPF");

        jLbl_date_GME.setText("Data de Nascimento");

        jLbl_senha_GME.setText("Senha");

        jLbl_nivel_GME.setText("Nível");

        jChbAtivo_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChbAtivo_GMEActionPerformed(evt);
            }
        });

        jCboNivel_GME.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "administrador", "funcionario", "vendedor", "gerente" }));
        jCboNivel_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboNivel_GMEActionPerformed(evt);
            }
        });

        jLbl_ativo_GME.setText("Ativo");

        jBtnIncluir_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnIncluir_GME.setText("Incluir");
        jBtnIncluir_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluir_GMEActionPerformed(evt);
            }
        });

        jBtnAlterar_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar_1.png"))); // NOI18N
        jBtnAlterar_GME.setText("Alterar");
        jBtnAlterar_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterar_GMEActionPerformed(evt);
            }
        });

        jBtnExcluir_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir_1.png"))); // NOI18N
        jBtnExcluir_GME.setText("Excluir");
        jBtnExcluir_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluir_GMEActionPerformed(evt);
            }
        });

        jBtnConfirmar_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        jBtnConfirmar_GME.setText("Confirmar");
        jBtnConfirmar_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmar_GMEActionPerformed(evt);
            }
        });

        jBtnCancelar_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar_1.png"))); // NOI18N
        jBtnCancelar_GME.setText("Cancelar");
        jBtnCancelar_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelar_GMEActionPerformed(evt);
            }
        });

        jBtnPesquisar_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnPesquisar_GME.setText("Pesquisar");
        jBtnPesquisar_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisar_GMEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTxtApelido_GME, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                        .addComponent(jTxtNome_GME))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPwfSenha_GME, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                .addComponent(jLbl_senha_GME)
                                .addComponent(jFmtCpf_GME))
                            .addComponent(jLbl_cpf_GME)
                            .addComponent(jLbl_codigo_GME)
                            .addComponent(jLbl_nome_GME)
                            .addComponent(jLbl_apelido_GME)
                            .addComponent(jTxtCodigo_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLbl_date_GME)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLbl_nivel_GME)
                                    .addComponent(jCboNivel_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFmtDataDeNascimento_GME))
                                .addGap(25, 25, 25)
                                .addComponent(jChbAtivo_GME)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLbl_ativo_GME)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jBtnIncluir_GME)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnAlterar_GME)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnExcluir_GME)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnConfirmar_GME)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnCancelar_GME)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnPesquisar_GME)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLbl_codigo_GME)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtCodigo_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLbl_nome_GME)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtNome_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLbl_apelido_GME)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtApelido_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbl_cpf_GME)
                            .addComponent(jLbl_date_GME))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jFmtDataDeNascimento_GME, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jFmtCpf_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jChbAtivo_GME)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLbl_ativo_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl_senha_GME)
                    .addComponent(jLbl_nivel_GME))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPwfSenha_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboNivel_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnIncluir_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnAlterar_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnConfirmar_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnCancelar_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnPesquisar_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBtnExcluir_GME, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtNome_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNome_GMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNome_GMEActionPerformed

    private void jBtnIncluir_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluir_GMEActionPerformed

        incluir = true;
        Util_GME.habilitar(true, jTxtCodigo_GME, jTxtNome_GME, jTxtApelido_GME, jFmtCpf_GME,
                jFmtDataDeNascimento_GME, jCboNivel_GME, jChbAtivo_GME, jPwfSenha_GME, jBtnConfirmar_GME, jBtnCancelar_GME);
        Util_GME.habilitar(false, jBtnIncluir_GME, jBtnPesquisar_GME);

        jTxtCodigo_GME.grabFocus();
    }//GEN-LAST:event_jBtnIncluir_GMEActionPerformed

    private void jBtnAlterar_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterar_GMEActionPerformed
        incluir = false;
        Util_GME.habilitar(true, jTxtCodigo_GME, jTxtNome_GME, jTxtApelido_GME, jFmtCpf_GME,
                jFmtDataDeNascimento_GME, jCboNivel_GME, jChbAtivo_GME, jPwfSenha_GME, jBtnConfirmar_GME, jBtnCancelar_GME);
        Util_GME.habilitar(false, jTxtCodigo_GME, jBtnAlterar_GME);

    }//GEN-LAST:event_jBtnAlterar_GMEActionPerformed

    private void jBtnExcluir_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluir_GMEActionPerformed
        if (Util_GME.perguntar("Deseja excluir esse registro de Usuario?") == true) {
            
            UsuariosDAO lvbUsuariosDAO = new UsuariosDAO();
            lvbUsuariosDAO.delete(viewBean());
            
            Util_GME.Limpar(jTxtCodigo_GME, jTxtNome_GME, jTxtApelido_GME, jFmtCpf_GME,
                    jFmtDataDeNascimento_GME, jCboNivel_GME, jChbAtivo_GME, jPwfSenha_GME);

            Util_GME.habilitar(false, jTxtCodigo_GME, jTxtNome_GME, jTxtApelido_GME, jFmtCpf_GME,
                    jFmtDataDeNascimento_GME, jCboNivel_GME, jChbAtivo_GME, jPwfSenha_GME,
                    jBtnAlterar_GME, jBtnConfirmar_GME, jBtnExcluir_GME, jBtnCancelar_GME
            );
            Util_GME.habilitar(true, jBtnIncluir_GME, jBtnPesquisar_GME);
        } else {

        }
    }//GEN-LAST:event_jBtnExcluir_GMEActionPerformed


    private void jBtnConfirmar_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmar_GMEActionPerformed

        UsuariosDAO usuariosDAO = new UsuariosDAO();
        if (incluir == true) {

            usuariosDAO.insert(viewBean());

        } else {

            usuariosDAO.update(viewBean());
        }

        Util_GME.Limpar(jTxtCodigo_GME, jTxtNome_GME, jTxtApelido_GME, jFmtCpf_GME,
                jFmtDataDeNascimento_GME, jCboNivel_GME, jChbAtivo_GME, jPwfSenha_GME);
        Util_GME.habilitar(false, jTxtCodigo_GME, jTxtNome_GME, jTxtApelido_GME, jFmtCpf_GME,
                jFmtDataDeNascimento_GME, jCboNivel_GME, jChbAtivo_GME, jPwfSenha_GME,
                jBtnAlterar_GME, jBtnConfirmar_GME, jBtnExcluir_GME, jBtnCancelar_GME);
        Util_GME.habilitar(true, jBtnIncluir_GME, jBtnPesquisar_GME);
    }//GEN-LAST:event_jBtnConfirmar_GMEActionPerformed

    private void jBtnPesquisar_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisar_GMEActionPerformed
        JDlgUsuariosPesquisar_GME jDlgUsuariosPesquisar_GME = new JDlgUsuariosPesquisar_GME(null, true);
        jDlgUsuariosPesquisar_GME.setTelaAnterior(this);
        jDlgUsuariosPesquisar_GME.setVisible(true);

        incluir = true;

        Util_GME.habilitar(false, jTxtCodigo_GME, jTxtNome_GME, jTxtApelido_GME, jFmtCpf_GME,
                jFmtDataDeNascimento_GME, jCboNivel_GME, jChbAtivo_GME, jPwfSenha_GME, jBtnIncluir_GME, jBtnPesquisar_GME
        );
        Util_GME.habilitar(true, jBtnAlterar_GME, jBtnExcluir_GME, jBtnCancelar_GME);
    }//GEN-LAST:event_jBtnPesquisar_GMEActionPerformed

    private void jBtnCancelar_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelar_GMEActionPerformed

        //System.out.println("incluir = " + incluir);
        //if((Util_GME.perguntar("Deseja cancelar esse registro de Usuario?") == true)){
        //    if(incluir == true){
        //      Util_GME.habilitar(false, jTxtCodigo_GME, jTxtNome_GME, jTxtApelido_GME, jFmtCpf_GME,
        //       jFmtDataDeNascimento_GME, jCboNivel_GME, jChbAtivo_GME, jPwfSenha_GME,
        //
        //       jBtnConfirmar_GME, jBtnCancelar_GME, jBtnAlterar_GME,jBtnExcluir_GME
        //         );
        //       Util_GME.habilitar(true, jBtnIncluir_GME,jBtnPesquisar_GME);
        //    }
        //    else{
        //        Util_GME.habilitar(false, jTxtCodigo_GME, jTxtNome_GME, jTxtApelido_GME, jFmtCpf_GME,
        //         jFmtDataDeNascimento_GME, jCboNivel_GME, jChbAtivo_GME, jPwfSenha_GME,jBtnIncluir_GME, jBtnPesquisar_GME, jBtnConfirmar_GME
        // 
        //         );
        //         Util_GME.habilitar(true,jBtnAlterar_GME,jBtnExcluir_GME);
        //
        //      }
        //  }
        //  else{
        //                        MEGA FUNÇÃO PARA FAZRE O CANCELAR RECONHCER DEPOIS DE QUEM QUE ELE FOI ATIVADO!
        //  }
        if (Util_GME.perguntar("Deseja cancelar esse registro de Usuarios?") == true) {

            Util_GME.Limpar(jTxtCodigo_GME, jTxtNome_GME, jTxtApelido_GME, jFmtCpf_GME,
                    jFmtDataDeNascimento_GME, jCboNivel_GME, jChbAtivo_GME, jPwfSenha_GME);

            Util_GME.habilitar(false, jTxtCodigo_GME, jTxtNome_GME, jTxtApelido_GME, jFmtCpf_GME,
                    jFmtDataDeNascimento_GME, jCboNivel_GME, jChbAtivo_GME, jPwfSenha_GME,
                    jBtnAlterar_GME, jBtnConfirmar_GME, jBtnExcluir_GME, jBtnCancelar_GME
            );

            Util_GME.habilitar(true, jBtnIncluir_GME, jBtnPesquisar_GME
            );

        }

    }//GEN-LAST:event_jBtnCancelar_GMEActionPerformed

    private void jTxtCodigo_GMEFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtCodigo_GMEFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_jTxtCodigo_GMEFocusLost

    private void jCboNivel_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboNivel_GMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboNivel_GMEActionPerformed

    private void jChbAtivo_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChbAtivo_GMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChbAtivo_GMEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios_GME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios_GME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios_GME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios_GME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgUsuarios_GME dialog = new JDlgUsuarios_GME(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar_GME;
    private javax.swing.JButton jBtnCancelar_GME;
    private javax.swing.JButton jBtnConfirmar_GME;
    private javax.swing.JButton jBtnExcluir_GME;
    private javax.swing.JButton jBtnIncluir_GME;
    private javax.swing.JButton jBtnPesquisar_GME;
    private javax.swing.JComboBox<String> jCboNivel_GME;
    private javax.swing.JCheckBox jChbAtivo_GME;
    private javax.swing.JFormattedTextField jFmtCpf_GME;
    private javax.swing.JFormattedTextField jFmtDataDeNascimento_GME;
    private javax.swing.JLabel jLbl_apelido_GME;
    private javax.swing.JLabel jLbl_ativo_GME;
    private javax.swing.JLabel jLbl_codigo_GME;
    private javax.swing.JLabel jLbl_cpf_GME;
    private javax.swing.JLabel jLbl_date_GME;
    private javax.swing.JLabel jLbl_nivel_GME;
    private javax.swing.JLabel jLbl_nome_GME;
    private javax.swing.JLabel jLbl_senha_GME;
    private javax.swing.JPasswordField jPwfSenha_GME;
    private javax.swing.JTextField jTxtApelido_GME;
    private javax.swing.JTextField jTxtCodigo_GME;
    private javax.swing.JTextField jTxtNome_GME;
    // End of variables declaration//GEN-END:variables
}
