/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.Produtos;
import bean.Venda;
import bean.VendaProduto;
import dao.ProdutosDAO;
import dao.VendaDAO;
import dao.VendaProdutoDAO;
import java.util.List;
import tools.Util_GME;

/**
 *
 * @author u07273579130
 */
public class JDlgVendas_produtos_GME extends javax.swing.JDialog {

    /**
     * Creates new form JDlgVendas_produtos_GME
     */
    public JDlgVendas_produtos_GME(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Tela de Vendas Produtos");
        setLocationRelativeTo(null);
        jTxt_quantidade_GME.setText("1");
        Util_GME.habilitar(true, jCbxProduto_GME, jTxt_quantidade_GME,
                jBtn_OK_GME, jBtn_Sair_GME);
        Util_GME.habilitar(false, jTxt_ValorUnitario_GME, jTxt_code_GME, jTxt_Total_GME);
        ProdutosDAO produtosDAO = new ProdutosDAO();
        List listaPD = (List) produtosDAO.listAll();
        for (Object object : listaPD) {
            jCbxProduto_GME.addItem((Produtos) object);
        }

    }

    private boolean incluir;

    public VendaProduto viewBean() {
        VendaProduto vendaProduto = new VendaProduto();
        vendaProduto.setGmeIdVendaProduto(Util_GME.strToInt(jTxt_code_GME.getText()));

        vendaProduto.setProdutos((Produtos) jCbxProduto_GME.getSelectedItem());

        vendaProduto.setGmeQuantidade(Util_GME.strToInt(jTxt_quantidade_GME.getText()));
        vendaProduto.setGmeValorUnitario(Util_GME.strToDouble(jTxt_ValorUnitario_GME.getText()));

        return vendaProduto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxt_quantidade_GME = new javax.swing.JTextField();
        jLbl_Quantidade_GME = new javax.swing.JLabel();
        jTxt_ValorUnitario_GME = new javax.swing.JTextField();
        jLbl_ValorUnitario_GME = new javax.swing.JLabel();
        jBtn_OK_GME = new javax.swing.JButton();
        jTxt_code_GME = new javax.swing.JTextField();
        jBtn_Sair_GME = new javax.swing.JButton();
        jLbl_code_GME = new javax.swing.JLabel();
        jLbl_produto_GME = new javax.swing.JLabel();
        jCbxProduto_GME = new javax.swing.JComboBox<Produtos>();
        jLbl_Total_GME = new javax.swing.JLabel();
        jTxt_Total_GME = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTxt_quantidade_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_quantidade_GMEActionPerformed(evt);
            }
        });

        jLbl_Quantidade_GME.setText(" Quantidade");

        jTxt_ValorUnitario_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_ValorUnitario_GMEActionPerformed(evt);
            }
        });

        jLbl_ValorUnitario_GME.setText("Valor Unitario");

        jBtn_OK_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        jBtn_OK_GME.setText("Ok");
        jBtn_OK_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_OK_GMEActionPerformed(evt);
            }
        });

        jTxt_code_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_code_GMEActionPerformed(evt);
            }
        });

        jBtn_Sair_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit_1.png"))); // NOI18N
        jBtn_Sair_GME.setText("Sair");
        jBtn_Sair_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_Sair_GMEActionPerformed(evt);
            }
        });

        jLbl_code_GME.setText("Código");

        jLbl_produto_GME.setText("Produto Vendido");

        jCbxProduto_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbxProduto_GMEActionPerformed(evt);
            }
        });

        jLbl_Total_GME.setText("Valor total");

        jTxt_Total_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_Total_GMEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxt_code_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbl_code_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLbl_Total_GME)
                            .addComponent(jTxt_Total_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtn_OK_GME))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCbxProduto_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbl_produto_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxt_quantidade_GME)
                            .addComponent(jLbl_Quantidade_GME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtn_Sair_GME, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTxt_ValorUnitario_GME, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLbl_ValorUnitario_GME, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtn_Sair_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn_OK_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbl_produto_GME)
                            .addComponent(jLbl_Quantidade_GME)
                            .addComponent(jLbl_ValorUnitario_GME))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCbxProduto_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxt_quantidade_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxt_ValorUnitario_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbl_code_GME)
                            .addComponent(jLbl_Total_GME))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxt_code_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxt_Total_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxt_quantidade_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_quantidade_GMEActionPerformed
        if (jTxt_quantidade_GME.getText().isEmpty() == false) {
            Produtos produtos = (Produtos) jCbxProduto_GME.getSelectedItem();
            int quant = Util_GME.strToInt(jTxt_quantidade_GME.getText());
            jTxt_Total_GME.setText(Util_GME.doubleToStr(quant * produtos.getGmeValorUnitario()));
        } else {
            jTxt_Total_GME.setText("");
        }
    }//GEN-LAST:event_jTxt_quantidade_GMEActionPerformed

    private void jTxt_ValorUnitario_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_ValorUnitario_GMEActionPerformed

    }//GEN-LAST:event_jTxt_ValorUnitario_GMEActionPerformed

    private void jBtn_OK_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_OK_GMEActionPerformed
        incluir = true;

        VendaProdutoDAO vendaProdutoDAO = new VendaProdutoDAO();

        if (incluir == true) {

            vendaProdutoDAO.insert(viewBean());

        } else {

            vendaProdutoDAO.update(viewBean());
        }

        Util_GME.Limpar(jTxt_code_GME, jTxt_ValorUnitario_GME, jCbxProduto_GME, jTxt_quantidade_GME);

        Util_GME.habilitar(false, jTxt_code_GME, jTxt_ValorUnitario_GME, jCbxProduto_GME, jTxt_quantidade_GME,
                jBtn_OK_GME, jBtn_Sair_GME);


    }//GEN-LAST:event_jBtn_OK_GMEActionPerformed

    private void jTxt_code_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_code_GMEActionPerformed

    }//GEN-LAST:event_jTxt_code_GMEActionPerformed

    private void jBtn_Sair_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_Sair_GMEActionPerformed
        if (Util_GME.perguntar("Deseja cancelar esse registro de Venda Produto?") == true) {
            dispose();

        }
    }//GEN-LAST:event_jBtn_Sair_GMEActionPerformed

    private void jTxt_Total_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_Total_GMEActionPerformed

    }//GEN-LAST:event_jTxt_Total_GMEActionPerformed

    private void jCbxProduto_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbxProduto_GMEActionPerformed
        // TODO add your handling code here:
        Produtos produtos = (Produtos) jCbxProduto_GME.getSelectedItem();
        jTxt_ValorUnitario_GME.setText(Util_GME.doubleToStr(produtos.getGmeValorUnitario()));
        int quant = Util_GME.strToInt(jTxt_quantidade_GME.getText());
        jTxt_Total_GME.setText(Util_GME.doubleToStr(quant * produtos.getGmeValorUnitario()));
    }//GEN-LAST:event_jCbxProduto_GMEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas_produtos_GME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas_produtos_GME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas_produtos_GME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas_produtos_GME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgVendas_produtos_GME dialog = new JDlgVendas_produtos_GME(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_OK_GME;
    private javax.swing.JButton jBtn_Sair_GME;
    private javax.swing.JComboBox<Produtos> jCbxProduto_GME;
    private javax.swing.JLabel jLbl_Quantidade_GME;
    private javax.swing.JLabel jLbl_Total_GME;
    private javax.swing.JLabel jLbl_ValorUnitario_GME;
    private javax.swing.JLabel jLbl_code_GME;
    private javax.swing.JLabel jLbl_produto_GME;
    private javax.swing.JTextField jTxt_Total_GME;
    private javax.swing.JTextField jTxt_ValorUnitario_GME;
    private javax.swing.JTextField jTxt_code_GME;
    private javax.swing.JTextField jTxt_quantidade_GME;
    // End of variables declaration//GEN-END:variables
}
