/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import bean.Produtos;
import dao.ProdutosDAO;
import tools.Util_GME;

/**
 *
 * @author guilh
 */
public class JDlgProdutos_GME extends javax.swing.JDialog {

    /**
     * Creates new form jDlgProdutos_GME
     */
    public JDlgProdutos_GME(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Tela de Cadastro de Produtos");
        setLocationRelativeTo(null);
        Util_GME.habilitar(false, jTxtNome_GME, jTxtValor_GME, jTxt_Catagoria_GME, jTxt_Codigo_GME, jCboACUCAR_GME,
                jCboLitragemXQuant_GME, jCboSabor_GME, jCbo_categoria_GME, jCbx_Edição_Limitadal_GME,
                jBtnAlterar_GME, jBtnExcluir_GME, jBtnConfirmar_GME, jBtnCancelar_GME);
    }

    private boolean incluir;

    public Produtos viewBean() {
        Produtos produto = new Produtos();

        produto.setGmeIdProdutos(Util_GME.strToInt(jTxt_Codigo_GME.getText()));
        produto.setGmeNomeProduto(jTxtNome_GME.getText());
        produto.setGmeValorUnitario(Util_GME.strToDouble(jTxtValor_GME.getText()));

        produto.setGmeCategoria(jCbo_categoria_GME.getSelectedIndex());
        produto.setGmeSabor(jCboSabor_GME.getSelectedItem().toString());
        produto.setGmeAcucar(jCboACUCAR_GME.getSelectedIndex());
        produto.setGmeLitragem(jCboLitragemXQuant_GME.getSelectedIndex());

        if (jCbx_Edição_Limitadal_GME.isSelected()) {
            produto.setGmeEdicaoLimitada("S");
        } else {
            produto.setGmeEdicaoLimitada("N");
        }
        return produto;
    }
    
    public void beanView(Produtos produto) {
    jTxt_Codigo_GME.setText(Util_GME.intToStr(produto.getGmeIdProdutos()));
    jTxtNome_GME.setText(produto.getGmeNomeProduto());
    jTxtValor_GME.setText(Util_GME.doubleToStr(produto.getGmeValorUnitario()));

    jCbo_categoria_GME.setSelectedItem(produto.getGmeCategoria());
    jCboSabor_GME.setSelectedItem(produto.getGmeSabor());
    jCboACUCAR_GME.setSelectedItem(produto.getGmeAcucar());
    jCboLitragemXQuant_GME.setSelectedItem(produto.getGmeLitragem());
    if (produto.getGmeEdicaoLimitada().equals("S") == true){
        jCbx_Edição_Limitadal_GME.setSelected(true);
        }else{
        jCbx_Edição_Limitadal_GME.setSelected(false);
        }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCboSabor_GME = new javax.swing.JComboBox<>();
        jBtnIncluir_GME = new javax.swing.JButton();
        jCboLitragemXQuant_GME = new javax.swing.JComboBox<>();
        Nome_GME = new javax.swing.JLabel();
        acucar_GME = new javax.swing.JLabel();
        jTxtNome_GME = new javax.swing.JTextField();
        jCboACUCAR_GME = new javax.swing.JComboBox<>();
        Sabor_GME = new javax.swing.JLabel();
        jCbo_categoria_GME = new javax.swing.JComboBox<>();
        Valor_GME = new javax.swing.JLabel();
        jTxtValor_GME = new javax.swing.JTextField();
        jCbx_Edição_Limitadal_GME = new javax.swing.JCheckBox();
        jBtnConfirmar_GME = new javax.swing.JButton();
        codigo_GME = new javax.swing.JLabel();
        jBtnExcluir_GME = new javax.swing.JButton();
        jTxt_Codigo_GME = new javax.swing.JTextField();
        jBtnCancelar_GME = new javax.swing.JButton();
        jTxt_Catagoria_GME = new javax.swing.JLabel();
        jBtnPesquisar_GME = new javax.swing.JButton();
        LitragemXQuant_GME = new javax.swing.JLabel();
        jBtnAlterar_GME = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jCboSabor_GME.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tradicional", "Melancia com kiuwi", "Tropical", "Açai com coco", "Citrus", "Abacaxi com Hortelã", "Maça verde", " " }));

        jBtnIncluir_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir_1.png"))); // NOI18N
        jBtnIncluir_GME.setText("Incluir");
        jBtnIncluir_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluir_GMEActionPerformed(evt);
            }
        });

        jCboLitragemXQuant_GME.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "24 X 200ML", "12 X 200ML", "6 X 200ML", "24 X 250ML", "12 x 250ML", "6 X 250ML", "24 X 480ML", "12 X 480ML", "6 X 480ML", "6 X 1L", "6 X 2L" }));

        Nome_GME.setText("Nome");

        acucar_GME.setText("Adição de açucar");

        jCboACUCAR_GME.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Com adição", "Zero açucar" }));

        Sabor_GME.setText("Sabor");

        jCbo_categoria_GME.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Citricos", "Doces", "OGs", "importados" }));

        Valor_GME.setText("Valor Unitario");

        jCbx_Edição_Limitadal_GME.setText("Edição Limitada");
        jCbx_Edição_Limitadal_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbx_Edição_Limitadal_GMEActionPerformed(evt);
            }
        });

        jBtnConfirmar_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        jBtnConfirmar_GME.setText("Confirmar");
        jBtnConfirmar_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmar_GMEActionPerformed(evt);
            }
        });

        codigo_GME.setText("Código [ID]");

        jBtnExcluir_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir_1.png"))); // NOI18N
        jBtnExcluir_GME.setText("Excluir");
        jBtnExcluir_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluir_GMEActionPerformed(evt);
            }
        });

        jBtnCancelar_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar_1.png"))); // NOI18N
        jBtnCancelar_GME.setText("Cancelar");
        jBtnCancelar_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelar_GMEActionPerformed(evt);
            }
        });

        jTxt_Catagoria_GME.setText("Categoria");

        jBtnPesquisar_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar_1.png"))); // NOI18N
        jBtnPesquisar_GME.setText("Pesquisar");
        jBtnPesquisar_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisar_GMEActionPerformed(evt);
            }
        });

        LitragemXQuant_GME.setText("Quantidae X Litragem");

        jBtnAlterar_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar_1.png"))); // NOI18N
        jBtnAlterar_GME.setText("Alterar");
        jBtnAlterar_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterar_GMEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnIncluir_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Valor_GME)
                                .addComponent(jTxtValor_GME)
                                .addComponent(jTxtNome_GME)
                                .addComponent(Nome_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Sabor_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnAlterar_GME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxt_Catagoria_GME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCboSabor_GME, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCbo_categoria_GME, 0, 1, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCboLitragemXQuant_GME, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LitragemXQuant_GME)
                                        .addGap(46, 46, 46)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(acucar_GME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap())
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jCboACUCAR_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(254, 254, 254))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jBtnExcluir_GME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnConfirmar_GME)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnCancelar_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnPesquisar_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCbx_Edição_Limitadal_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(codigo_GME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTxt_Codigo_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Sabor_GME)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Nome_GME)
                                    .addComponent(acucar_GME, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTxtNome_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCboSabor_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCboLitragemXQuant_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCboACUCAR_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(LitragemXQuant_GME))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Valor_GME)
                            .addComponent(jTxt_Catagoria_GME))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtValor_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCbo_categoria_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCbx_Edição_Limitadal_GME))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(codigo_GME)
                .addGap(7, 7, 7)
                .addComponent(jTxt_Codigo_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnAlterar_GME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnExcluir_GME, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnConfirmar_GME, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jBtnIncluir_GME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnCancelar_GME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnPesquisar_GME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnIncluir_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluir_GMEActionPerformed

        Util_GME.habilitar(true, jTxtNome_GME, jTxtValor_GME, jTxt_Catagoria_GME, jTxt_Codigo_GME, jCboACUCAR_GME,
                jCboLitragemXQuant_GME, jCboSabor_GME, jCbo_categoria_GME, jCbx_Edição_Limitadal_GME,
                jBtnConfirmar_GME, jBtnCancelar_GME);
        Util_GME.habilitar(false, jBtnIncluir_GME, jBtnPesquisar_GME, jBtnAlterar_GME, jBtnExcluir_GME);
    }//GEN-LAST:event_jBtnIncluir_GMEActionPerformed

    private void jBtnConfirmar_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmar_GMEActionPerformed
        incluir = true;
        
        ProdutosDAO produtosDAO = new ProdutosDAO();
        
        if (incluir == true) {

            produtosDAO.insert(viewBean());

        } else {

            produtosDAO.update(viewBean());
        }
        
        Util_GME.Limpar(jTxtNome_GME, jTxtValor_GME, jTxt_Catagoria_GME, jTxt_Codigo_GME, jCboACUCAR_GME,
                jCboLitragemXQuant_GME, jCboSabor_GME, jCbo_categoria_GME, jCbx_Edição_Limitadal_GME);

        Util_GME.habilitar(false, jTxtNome_GME, jTxtValor_GME, jTxt_Catagoria_GME, jTxt_Codigo_GME, jCboACUCAR_GME,
                jCboLitragemXQuant_GME, jCboSabor_GME, jCbo_categoria_GME, jCbx_Edição_Limitadal_GME,
                jBtnAlterar_GME, jBtnExcluir_GME, jBtnConfirmar_GME, jBtnCancelar_GME);
        Util_GME.habilitar(true, jBtnIncluir_GME, jBtnPesquisar_GME);
    }//GEN-LAST:event_jBtnConfirmar_GMEActionPerformed

    private void jBtnExcluir_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluir_GMEActionPerformed
        if (Util_GME.perguntar("Deseja excluir esse registro de Produto?") == true) {
            Util_GME.Limpar(jTxtNome_GME, jTxtValor_GME, jTxt_Catagoria_GME, jTxt_Codigo_GME, jCboACUCAR_GME,
                    jCboLitragemXQuant_GME, jCboSabor_GME, jCbo_categoria_GME, jCbx_Edição_Limitadal_GME);

            Util_GME.habilitar(false, jTxtNome_GME, jTxtValor_GME, jTxt_Catagoria_GME, jTxt_Codigo_GME, jCboACUCAR_GME,
                    jCboLitragemXQuant_GME, jCboSabor_GME, jCbo_categoria_GME, jCbx_Edição_Limitadal_GME,
                    jBtnAlterar_GME, jBtnExcluir_GME, jBtnConfirmar_GME, jBtnCancelar_GME);
            Util_GME.habilitar(true, jBtnIncluir_GME, jBtnPesquisar_GME);
        }
    }//GEN-LAST:event_jBtnExcluir_GMEActionPerformed

    private void jBtnCancelar_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelar_GMEActionPerformed
        if (Util_GME.perguntar("Deseja cancelar esse registro de Produto?") == true) {
            Util_GME.Limpar(jTxtNome_GME, jTxtValor_GME, jTxt_Catagoria_GME, jTxt_Codigo_GME, jCboACUCAR_GME,
                    jCboLitragemXQuant_GME, jCboSabor_GME, jCbo_categoria_GME, jCbx_Edição_Limitadal_GME);

            Util_GME.habilitar(false, jTxtNome_GME, jTxtValor_GME, jTxt_Catagoria_GME, jTxt_Codigo_GME, jCboACUCAR_GME,
                    jCboLitragemXQuant_GME, jCboSabor_GME, jCbo_categoria_GME, jCbx_Edição_Limitadal_GME,
                    jBtnAlterar_GME, jBtnExcluir_GME, jBtnConfirmar_GME, jBtnCancelar_GME);
            Util_GME.habilitar(true, jBtnIncluir_GME, jBtnPesquisar_GME);
        }
    }//GEN-LAST:event_jBtnCancelar_GMEActionPerformed

    private void jBtnPesquisar_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisar_GMEActionPerformed
        JDlgProdutosPesquisar_GME jDlgProdutosPesquisar_GME = new JDlgProdutosPesquisar_GME(null, true);
        jDlgProdutosPesquisar_GME.setVisible(true);

        Util_GME.habilitar(false, jTxtNome_GME, jTxtValor_GME, jTxt_Catagoria_GME, jTxt_Codigo_GME, jCboACUCAR_GME,
                jCboLitragemXQuant_GME, jCboSabor_GME, jCbo_categoria_GME, jCbx_Edição_Limitadal_GME,
                jBtnIncluir_GME, jBtnPesquisar_GME, jBtnConfirmar_GME);
        Util_GME.habilitar(true, jBtnAlterar_GME, jBtnExcluir_GME, jBtnCancelar_GME);
    }//GEN-LAST:event_jBtnPesquisar_GMEActionPerformed

    private void jBtnAlterar_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterar_GMEActionPerformed
        incluir = false;
        
        Util_GME.habilitar(true, jTxtNome_GME, jTxtValor_GME, jTxt_Catagoria_GME, jCboACUCAR_GME,
                jCboLitragemXQuant_GME, jCboSabor_GME, jCbo_categoria_GME, jCbx_Edição_Limitadal_GME,
                jBtnExcluir_GME, jBtnCancelar_GME, jBtnConfirmar_GME);
        Util_GME.habilitar(false, jBtnAlterar_GME, jBtnIncluir_GME, jBtnPesquisar_GME);
    }//GEN-LAST:event_jBtnAlterar_GMEActionPerformed

    private void jCbx_Edição_Limitadal_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbx_Edição_Limitadal_GMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbx_Edição_Limitadal_GMEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgProdutos_GME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgProdutos_GME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgProdutos_GME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgProdutos_GME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgProdutos_GME dialog = new JDlgProdutos_GME(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LitragemXQuant_GME;
    private javax.swing.JLabel Nome_GME;
    private javax.swing.JLabel Sabor_GME;
    private javax.swing.JLabel Valor_GME;
    private javax.swing.JLabel acucar_GME;
    private javax.swing.JLabel codigo_GME;
    private javax.swing.JButton jBtnAlterar_GME;
    private javax.swing.JButton jBtnCancelar_GME;
    private javax.swing.JButton jBtnConfirmar_GME;
    private javax.swing.JButton jBtnExcluir_GME;
    private javax.swing.JButton jBtnIncluir_GME;
    private javax.swing.JButton jBtnPesquisar_GME;
    private javax.swing.JComboBox<String> jCboACUCAR_GME;
    private javax.swing.JComboBox<String> jCboLitragemXQuant_GME;
    private javax.swing.JComboBox<String> jCboSabor_GME;
    private javax.swing.JComboBox<String> jCbo_categoria_GME;
    private javax.swing.JCheckBox jCbx_Edição_Limitadal_GME;
    private javax.swing.JTextField jTxtNome_GME;
    private javax.swing.JTextField jTxtValor_GME;
    private javax.swing.JLabel jTxt_Catagoria_GME;
    private javax.swing.JTextField jTxt_Codigo_GME;
    // End of variables declaration//GEN-END:variables
}
