/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import bean.Empresas;
import dao.EmpresasDAO;
import tools.Util_GME;

/**
 *
 * @author guilh
 */
public class JDlgEmpresas_GME extends javax.swing.JDialog {

    /**
     * Creates new form jDlgEmpresas_GME
     */
    public JDlgEmpresas_GME(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Tela de Cadastro de Empresas");
        setLocationRelativeTo(null);

        Util_GME.habilitar(false, jTxtCodigo_GME, jTxtNomeEMPRE_GME, jTxtNomeREP_GME, jTxtnumero_GME, jTxtCodigo_GME,
                jTxtnumero_GME, jFmt_CEP_GME, jFmt_TEL_EMPRE_GME, jFmt_TEL_REP_GME, jFmt_cnpj_GME, jBtnCancelar_GME,
                jBtnConfirmar_GME, jBtnExcluir_GME, jBtnAlterar_GME);
        Util_GME.habilitar(true, jBtnIncluir_GME, jBtnPesquisar_GME);
    }

    private boolean incluir;

    public Empresas viewBean() {
        Empresas empresa = new Empresas();

        empresa.setGmeIdEmpresas(Util_GME.strToInt(jTxtCodigo_GME.getText()));
        empresa.setGmeNomeEmpresa(jTxtNomeEMPRE_GME.getText());
        empresa.setGmeNomeRepresentante(jTxtNomeREP_GME.getText());
        empresa.setGmeNumero(jTxtnumero_GME.getText());
        empresa.setGmeCep(jFmt_CEP_GME.getText());
        empresa.setGmeTelefoneEmpresa(jFmt_TEL_EMPRE_GME.getText());
        empresa.setGmeTelefoneRepresentante(jFmt_TEL_REP_GME.getText());
        empresa.setGmeCnpj(jFmt_cnpj_GME.getText());

        return empresa;
    }

    public void beanView(Empresas empresa) {
        jTxtCodigo_GME.setText(Util_GME.intToStr(empresa.getGmeIdEmpresas()));
        jTxtNomeEMPRE_GME.setText(empresa.getGmeNomeEmpresa());
        jTxtNomeREP_GME.setText(empresa.getGmeNomeRepresentante());
        jTxtnumero_GME.setText(empresa.getGmeNumero());

        jFmt_CEP_GME.setText(empresa.getGmeCep());
        jFmt_TEL_EMPRE_GME.setText(empresa.getGmeTelefoneEmpresa());
        jFmt_TEL_REP_GME.setText(empresa.getGmeTelefoneRepresentante());
        jFmt_cnpj_GME.setText(empresa.getGmeCnpj());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtCodigo_GME = new javax.swing.JTextField();
        jBtnAlterar_GME = new javax.swing.JButton();
        numero_GME = new javax.swing.JLabel();
        jBtnIncluir_GME = new javax.swing.JButton();
        jTxtnumero_GME = new javax.swing.JTextField();
        nome_GME = new javax.swing.JLabel();
        CNPJ_GME = new javax.swing.JLabel();
        jTxtNomeEMPRE_GME = new javax.swing.JTextField();
        jFmt_CEP_GME = new javax.swing.JFormattedTextField();
        CEP_GME = new javax.swing.JLabel();
        jFmt_TEL_EMPRE_GME = new javax.swing.JFormattedTextField();
        Telefone_GME = new javax.swing.JLabel();
        jFmt_cnpj_GME = new javax.swing.JFormattedTextField();
        TelefonePessoal_GME = new javax.swing.JLabel();
        jFmt_TEL_REP_GME = new javax.swing.JFormattedTextField();
        jBtnConfirmar_GME = new javax.swing.JButton();
        jTxtNomeREP_GME = new javax.swing.JTextField();
        jBtnExcluir_GME = new javax.swing.JButton();
        Cargo_GME = new javax.swing.JLabel();
        jBtnCancelar_GME = new javax.swing.JButton();
        codigo_GME = new javax.swing.JLabel();
        jBtnPesquisar_GME = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBtnAlterar_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar_1.png"))); // NOI18N
        jBtnAlterar_GME.setText("Alterar");
        jBtnAlterar_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterar_GMEActionPerformed(evt);
            }
        });

        numero_GME.setText("Número [LOC]");

        jBtnIncluir_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnIncluir_GME.setText("Incluir");
        jBtnIncluir_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluir_GMEActionPerformed(evt);
            }
        });

        nome_GME.setText("Nome da empresa");

        CNPJ_GME.setText("CNPJ ");

        try {
            jFmt_CEP_GME.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        CEP_GME.setText("CEP");

        try {
            jFmt_TEL_EMPRE_GME.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##).#.####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFmt_TEL_EMPRE_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmt_TEL_EMPRE_GMEActionPerformed(evt);
            }
        });

        Telefone_GME.setText("Telefone da empresa");

        try {
            jFmt_cnpj_GME.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        TelefonePessoal_GME.setText("nome do representante");

        try {
            jFmt_TEL_REP_GME.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##).#.####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jBtnConfirmar_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        jBtnConfirmar_GME.setText("Confirmar");
        jBtnConfirmar_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmar_GMEActionPerformed(evt);
            }
        });

        jTxtNomeREP_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNomeREP_GMEActionPerformed(evt);
            }
        });

        jBtnExcluir_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir_1.png"))); // NOI18N
        jBtnExcluir_GME.setText("Excluir");
        jBtnExcluir_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluir_GMEActionPerformed(evt);
            }
        });

        Cargo_GME.setText("Telefone do Representante");

        jBtnCancelar_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar_1.png"))); // NOI18N
        jBtnCancelar_GME.setText("Cancelar");
        jBtnCancelar_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelar_GMEActionPerformed(evt);
            }
        });

        codigo_GME.setText("Codigo [ID]");

        jBtnPesquisar_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnPesquisar_GME.setText("Pesquisar");
        jBtnPesquisar_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisar_GMEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtnIncluir_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTxtNomeEMPRE_GME)
                                        .addComponent(nome_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jFmt_CEP_GME, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(CEP_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFmt_TEL_EMPRE_GME)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jBtnAlterar_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Telefone_GME)
                                            .addComponent(CNPJ_GME))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jFmt_cnpj_GME)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxtnumero_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnExcluir_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnConfirmar_GME)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnCancelar_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnPesquisar_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Cargo_GME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTxtNomeREP_GME)
                                        .addComponent(TelefonePessoal_GME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jFmt_TEL_REP_GME))
                                    .addComponent(jTxtCodigo_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(codigo_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numero_GME, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TelefonePessoal_GME)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtNomeREP_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Cargo_GME)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFmt_TEL_REP_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(codigo_GME)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCodigo_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nome_GME)
                            .addComponent(Telefone_GME))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtNomeEMPRE_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmt_TEL_EMPRE_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CEP_GME)
                            .addComponent(CNPJ_GME))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFmt_CEP_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmt_cnpj_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numero_GME)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtnumero_GME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnAlterar_GME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnExcluir_GME, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnConfirmar_GME, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(jBtnIncluir_GME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnCancelar_GME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnPesquisar_GME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAlterar_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterar_GMEActionPerformed
        incluir = false;
        
        
        
        Util_GME.habilitar(true, jTxtNomeEMPRE_GME, jTxtNomeREP_GME, jTxtnumero_GME, jTxtnumero_GME,
                jFmt_CEP_GME, jFmt_TEL_EMPRE_GME, jFmt_TEL_REP_GME, jFmt_cnpj_GME,
                jBtnCancelar_GME, jBtnExcluir_GME, jBtnConfirmar_GME
        );
        Util_GME.habilitar(false, jBtnIncluir_GME, jBtnPesquisar_GME, jBtnAlterar_GME);
    }//GEN-LAST:event_jBtnAlterar_GMEActionPerformed

    private void jBtnIncluir_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluir_GMEActionPerformed
       incluir = true;
        
        Util_GME.habilitar(true, jTxtCodigo_GME, jTxtNomeEMPRE_GME, jTxtNomeREP_GME, jTxtnumero_GME, jTxtCodigo_GME,
                jTxtnumero_GME,
                jFmt_CEP_GME, jFmt_TEL_EMPRE_GME, jFmt_TEL_REP_GME, jFmt_cnpj_GME,
                jBtnCancelar_GME, jBtnConfirmar_GME
        );
        Util_GME.habilitar(false, jBtnIncluir_GME, jBtnPesquisar_GME, jBtnExcluir_GME, jBtnAlterar_GME);
    }//GEN-LAST:event_jBtnIncluir_GMEActionPerformed

    private void jBtnConfirmar_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmar_GMEActionPerformed
        EmpresasDAO empresasDAO = new EmpresasDAO();
        if (incluir == true) {

            empresasDAO.insert(viewBean());

        } else {

            empresasDAO.update(viewBean());
        }
        
        Util_GME.Limpar(jTxtCodigo_GME, jTxtNomeEMPRE_GME, jTxtNomeREP_GME, jTxtnumero_GME, jTxtCodigo_GME,
                jTxtnumero_GME, jFmt_CEP_GME, jFmt_TEL_EMPRE_GME, jFmt_TEL_REP_GME, jFmt_cnpj_GME,
                jBtnCancelar_GME, jBtnConfirmar_GME, jBtnExcluir_GME, jBtnAlterar_GME);

        Util_GME.habilitar(false, jTxtCodigo_GME, jTxtNomeEMPRE_GME, jTxtNomeREP_GME, jTxtnumero_GME, jTxtCodigo_GME,
                jTxtnumero_GME,
                jFmt_CEP_GME, jFmt_TEL_EMPRE_GME, jFmt_TEL_REP_GME, jFmt_cnpj_GME,
                jBtnCancelar_GME, jBtnConfirmar_GME, jBtnExcluir_GME, jBtnAlterar_GME
        );
        Util_GME.habilitar(true, jBtnIncluir_GME, jBtnPesquisar_GME);
    }//GEN-LAST:event_jBtnConfirmar_GMEActionPerformed

    private void jTxtNomeREP_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNomeREP_GMEActionPerformed

    }//GEN-LAST:event_jTxtNomeREP_GMEActionPerformed

    private void jBtnExcluir_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluir_GMEActionPerformed
        if (Util_GME.perguntar("Deseja excluir esse registro de Empresa?") == true) {
            EmpresasDAO empresasDAO = new EmpresasDAO();
            empresasDAO.delete(viewBean());
            
            Util_GME.Limpar(jTxtCodigo_GME, jTxtNomeEMPRE_GME, jTxtNomeREP_GME, jTxtnumero_GME, jTxtCodigo_GME,
                    jTxtnumero_GME, jFmt_CEP_GME, jFmt_TEL_EMPRE_GME, jFmt_TEL_REP_GME, jFmt_cnpj_GME,
                    jBtnCancelar_GME, jBtnConfirmar_GME, jBtnExcluir_GME, jBtnAlterar_GME);
        }
    }//GEN-LAST:event_jBtnExcluir_GMEActionPerformed

    private void jBtnCancelar_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelar_GMEActionPerformed
        if (Util_GME.perguntar("Deseja excluir esse registro de Empresa?") == true) {
            Util_GME.Limpar(jTxtCodigo_GME, jTxtNomeEMPRE_GME, jTxtNomeREP_GME, jTxtnumero_GME, jTxtCodigo_GME,
                    jTxtnumero_GME, jFmt_CEP_GME, jFmt_TEL_EMPRE_GME, jFmt_TEL_REP_GME, jFmt_cnpj_GME,
                    jBtnCancelar_GME, jBtnConfirmar_GME, jBtnExcluir_GME, jBtnAlterar_GME);

            Util_GME.habilitar(false, jTxtCodigo_GME, jTxtNomeEMPRE_GME, jTxtNomeREP_GME, jTxtnumero_GME, jTxtCodigo_GME,
                    jTxtnumero_GME,
                    jFmt_CEP_GME, jFmt_TEL_EMPRE_GME, jFmt_TEL_REP_GME, jFmt_cnpj_GME,
                    jBtnCancelar_GME, jBtnConfirmar_GME, jBtnExcluir_GME, jBtnAlterar_GME
            );
            Util_GME.habilitar(true, jBtnIncluir_GME, jBtnPesquisar_GME);
        }
    }//GEN-LAST:event_jBtnCancelar_GMEActionPerformed

    private void jBtnPesquisar_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisar_GMEActionPerformed
        JDlgEmpresasPesquisar_GME jDlgEmpresasPesquisar_GME = new JDlgEmpresasPesquisar_GME(null, true);
        jDlgEmpresasPesquisar_GME.setTelaAnterior(this);
        jDlgEmpresasPesquisar_GME.setVisible(true);

        Util_GME.habilitar(false, jTxtCodigo_GME, jTxtNomeEMPRE_GME, jTxtNomeREP_GME, jTxtnumero_GME, jTxtCodigo_GME,
                jTxtnumero_GME,
                jFmt_CEP_GME, jFmt_TEL_EMPRE_GME, jFmt_TEL_REP_GME, jFmt_cnpj_GME,
                jBtnIncluir_GME, jBtnPesquisar_GME
        );
        Util_GME.habilitar(true, jBtnExcluir_GME, jBtnAlterar_GME, jBtnCancelar_GME);
    }//GEN-LAST:event_jBtnPesquisar_GMEActionPerformed

    private void jFmt_TEL_EMPRE_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmt_TEL_EMPRE_GMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmt_TEL_EMPRE_GMEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgEmpresas_GME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgEmpresas_GME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgEmpresas_GME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgEmpresas_GME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgEmpresas_GME dialog = new JDlgEmpresas_GME(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CEP_GME;
    private javax.swing.JLabel CNPJ_GME;
    private javax.swing.JLabel Cargo_GME;
    private javax.swing.JLabel TelefonePessoal_GME;
    private javax.swing.JLabel Telefone_GME;
    private javax.swing.JLabel codigo_GME;
    private javax.swing.JButton jBtnAlterar_GME;
    private javax.swing.JButton jBtnCancelar_GME;
    private javax.swing.JButton jBtnConfirmar_GME;
    private javax.swing.JButton jBtnExcluir_GME;
    private javax.swing.JButton jBtnIncluir_GME;
    private javax.swing.JButton jBtnPesquisar_GME;
    private javax.swing.JFormattedTextField jFmt_CEP_GME;
    private javax.swing.JFormattedTextField jFmt_TEL_EMPRE_GME;
    private javax.swing.JFormattedTextField jFmt_TEL_REP_GME;
    private javax.swing.JFormattedTextField jFmt_cnpj_GME;
    private javax.swing.JTextField jTxtCodigo_GME;
    private javax.swing.JTextField jTxtNomeEMPRE_GME;
    private javax.swing.JTextField jTxtNomeREP_GME;
    private javax.swing.JTextField jTxtnumero_GME;
    private javax.swing.JLabel nome_GME;
    private javax.swing.JLabel numero_GME;
    // End of variables declaration//GEN-END:variables
}
