/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author guilh
 */
public class JFrmPrincipal_GME extends javax.swing.JFrame {

    /**
     * Creates new form JFrmPrincipal_
     */
    public JFrmPrincipal_GME() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        setTitle("SISTEMA DE VENDAS");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMnuSair_GME = new javax.swing.JMenu();
        jMnuUsuarios_GME = new javax.swing.JMenuItem();
        jMnuClientes_GME = new javax.swing.JMenuItem();
        jMnuEmpresas_GME = new javax.swing.JMenuItem();
        jMnuProdutos__GME = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMnuMovimento_GME = new javax.swing.JMenu();
        jMnuVenda_GME = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMnuSair_GME.setText("Cadastros");

        jMnuUsuarios_GME.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMnuUsuarios_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuario.png"))); // NOI18N
        jMnuUsuarios_GME.setText("Usuarios");
        jMnuUsuarios_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuUsuarios_GMEActionPerformed(evt);
            }
        });
        jMnuSair_GME.add(jMnuUsuarios_GME);

        jMnuClientes_GME.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMnuClientes_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cliente.png"))); // NOI18N
        jMnuClientes_GME.setText("Clientes");
        jMnuClientes_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuClientes_GMEActionPerformed(evt);
            }
        });
        jMnuSair_GME.add(jMnuClientes_GME);

        jMnuEmpresas_GME.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMnuEmpresas_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/grupo.png"))); // NOI18N
        jMnuEmpresas_GME.setText("Empresas");
        jMnuEmpresas_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuEmpresas_GMEActionPerformed(evt);
            }
        });
        jMnuSair_GME.add(jMnuEmpresas_GME);

        jMnuProdutos__GME.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMnuProdutos__GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produto.png"))); // NOI18N
        jMnuProdutos__GME.setText("Produtos");
        jMnuProdutos__GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuProdutos__GMEActionPerformed(evt);
            }
        });
        jMnuSair_GME.add(jMnuProdutos__GME);
        jMnuSair_GME.add(jSeparator2);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_BACK_SPACE, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit.png"))); // NOI18N
        jMenuItem1.setText("SAIR");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMnuSair_GME.add(jMenuItem1);

        jMenuBar1.add(jMnuSair_GME);

        jMnuMovimento_GME.setText("Movimento");

        jMnuVenda_GME.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMnuVenda_GME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar_1.png"))); // NOI18N
        jMnuVenda_GME.setText("Venda");
        jMnuVenda_GME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVenda_GMEActionPerformed(evt);
            }
        });
        jMnuMovimento_GME.add(jMnuVenda_GME);
        jMnuMovimento_GME.add(jSeparator1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produto_1.png"))); // NOI18N
        jMenuItem2.setText("Venda Produtos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMnuMovimento_GME.add(jMenuItem2);

        jMenuBar1.add(jMnuMovimento_GME);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuProdutos__GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuProdutos__GMEActionPerformed
        JDlgProdutos_GME  jDlgProdutos_GME = new  JDlgProdutos_GME(null,true);
        jDlgProdutos_GME.setVisible(true);
    }//GEN-LAST:event_jMnuProdutos__GMEActionPerformed

    private void jMnuEmpresas_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuEmpresas_GMEActionPerformed
     JDlgEmpresas_GME jDlgEmpresas_GME = new JDlgEmpresas_GME(null,true);
     jDlgEmpresas_GME.setVisible(true);
    }//GEN-LAST:event_jMnuEmpresas_GMEActionPerformed

    private void jMnuClientes_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuClientes_GMEActionPerformed
        JDlgClientes_GME jDlgClientes_GME = new JDlgClientes_GME(null, true);
        jDlgClientes_GME.setVisible(true);
    }//GEN-LAST:event_jMnuClientes_GMEActionPerformed

    private void jMnuUsuarios_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuUsuarios_GMEActionPerformed
        JDlgUsuarios_GME jDlgUsuarios_GME = new JDlgUsuarios_GME(null, true);
        jDlgUsuarios_GME.setVisible(true);
    }//GEN-LAST:event_jMnuUsuarios_GMEActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMnuVenda_GMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVenda_GMEActionPerformed
       JDlgVendas_GME jDlgVendas_GME = new JDlgVendas_GME(null,true);
       jDlgVendas_GME.setVisible(true);
    }//GEN-LAST:event_jMnuVenda_GMEActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JDlgVendas_produtos_GME jDlgVendas_produtos_GME = new JDlgVendas_produtos_GME(null,true);
        jDlgVendas_produtos_GME.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal_GME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal_GME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal_GME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal_GME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmPrincipal_GME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMnuClientes_GME;
    private javax.swing.JMenuItem jMnuEmpresas_GME;
    private javax.swing.JMenu jMnuMovimento_GME;
    private javax.swing.JMenuItem jMnuProdutos__GME;
    private javax.swing.JMenu jMnuSair_GME;
    private javax.swing.JMenuItem jMnuUsuarios_GME;
    private javax.swing.JMenuItem jMnuVenda_GME;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
