package bean;
// Generated 11/12/2025 09:40:56 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Clientes generated by hbm2java
 */
@Entity
@Table(name="clientes"
    ,catalog="db_giuliano_eidt"
)
public class Clientes  implements java.io.Serializable {


     private int gmeIdClientes;
     private String gmeNomePessoal;
     private String gmeEmailPessoal;
     private String gmeTelefonePessoal;
     private Date gmeDatanasc;
     private int gmeGenero;
     private int gmeEstadocivil;
     private String gmeCargo;
     private String gmeNomeLoja;
     private String gmeEmailLoja;
     private String gmeTelefoneLoja;
     private Date gmeDataCadastro;
     private String gmeCnpj;
     private String gmeCep;
     private String gmeNumero;
    

    public Clientes() {
    }

	
    public Clientes(String gmeNomePessoal, String gmeEmailPessoal, String gmeTelefonePessoal, Date gmeDatanasc, int gmeGenero, int gmeEstadocivil, String gmeCargo, String gmeNomeLoja, String gmeEmailLoja, String gmeTelefoneLoja, Date gmeDataCadastro, String gmeCnpj, String gmeCep, String gmeNumero) {
        this.gmeNomePessoal = gmeNomePessoal;
        this.gmeEmailPessoal = gmeEmailPessoal;
        this.gmeTelefonePessoal = gmeTelefonePessoal;
        this.gmeDatanasc = gmeDatanasc;
        this.gmeGenero = gmeGenero;
        this.gmeEstadocivil = gmeEstadocivil;
        this.gmeCargo = gmeCargo;
        this.gmeNomeLoja = gmeNomeLoja;
        this.gmeEmailLoja = gmeEmailLoja;
        this.gmeTelefoneLoja = gmeTelefoneLoja;
        this.gmeDataCadastro = gmeDataCadastro;
        this.gmeCnpj = gmeCnpj;
        this.gmeCep = gmeCep;
        this.gmeNumero = gmeNumero;
    }
    public Clientes(String gmeNomePessoal, String gmeEmailPessoal, String gmeTelefonePessoal, Date gmeDatanasc, int gmeGenero, int gmeEstadocivil, String gmeCargo, String gmeNomeLoja, String gmeEmailLoja, String gmeTelefoneLoja, Date gmeDataCadastro, String gmeCnpj, String gmeCep, String gmeNumero, Set vendas) {
       this.gmeNomePessoal = gmeNomePessoal;
       this.gmeEmailPessoal = gmeEmailPessoal;
       this.gmeTelefonePessoal = gmeTelefonePessoal;
       this.gmeDatanasc = gmeDatanasc;
       this.gmeGenero = gmeGenero;
       this.gmeEstadocivil = gmeEstadocivil;
       this.gmeCargo = gmeCargo;
       this.gmeNomeLoja = gmeNomeLoja;
       this.gmeEmailLoja = gmeEmailLoja;
       this.gmeTelefoneLoja = gmeTelefoneLoja;
       this.gmeDataCadastro = gmeDataCadastro;
       this.gmeCnpj = gmeCnpj;
       this.gmeCep = gmeCep;
       this.gmeNumero = gmeNumero;
       
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="gme_id_clientes", unique=true, nullable=false)
    public int getGmeIdClientes() {
        return this.gmeIdClientes;
    }
    
    public void setGmeIdClientes(int gmeIdClientes) {
        this.gmeIdClientes = gmeIdClientes;
    }

    
    @Column(name="gme_nome_pessoal", nullable=false, length=200)
    public String getGmeNomePessoal() {
        return this.gmeNomePessoal;
    }
    
    public void setGmeNomePessoal(String gmeNomePessoal) {
        this.gmeNomePessoal = gmeNomePessoal;
    }

    
    @Column(name="gme_email_pessoal", nullable=false, length=60)
    public String getGmeEmailPessoal() {
        return this.gmeEmailPessoal;
    }
    
    public void setGmeEmailPessoal(String gmeEmailPessoal) {
        this.gmeEmailPessoal = gmeEmailPessoal;
    }

    
    @Column(name="gme_telefone_pessoal", nullable=false, length=20)
    public String getGmeTelefonePessoal() {
        return this.gmeTelefonePessoal;
    }
    
    public void setGmeTelefonePessoal(String gmeTelefonePessoal) {
        this.gmeTelefonePessoal = gmeTelefonePessoal;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="gme_datanasc", nullable=false, length=10)
    public Date getGmeDatanasc() {
        return this.gmeDatanasc;
    }
    
    public void setGmeDatanasc(Date gmeDatanasc) {
        this.gmeDatanasc = gmeDatanasc;
    }

    
    @Column(name="gme_genero", nullable=false)
    public int getGmeGenero() {
        return this.gmeGenero;
    }
    
    public void setGmeGenero(int gmeGenero) {
        this.gmeGenero = gmeGenero;
    }

    
    @Column(name="gme_estadocivil", nullable=false)
    public int getGmeEstadocivil() {
        return this.gmeEstadocivil;
    }
    
    public void setGmeEstadocivil(int gmeEstadocivil) {
        this.gmeEstadocivil = gmeEstadocivil;
    }

    
    @Column(name="gme_cargo", nullable=false, length=30)
    public String getGmeCargo() {
        return this.gmeCargo;
    }
    
    public void setGmeCargo(String gmeCargo) {
        this.gmeCargo = gmeCargo;
    }

    
    @Column(name="gme_nome_loja", nullable=false, length=100)
    public String getGmeNomeLoja() {
        return this.gmeNomeLoja;
    }
    
    public void setGmeNomeLoja(String gmeNomeLoja) {
        this.gmeNomeLoja = gmeNomeLoja;
    }

    
    @Column(name="gme_email_loja", nullable=false, length=60)
    public String getGmeEmailLoja() {
        return this.gmeEmailLoja;
    }
    
    public void setGmeEmailLoja(String gmeEmailLoja) {
        this.gmeEmailLoja = gmeEmailLoja;
    }

    
    @Column(name="gme_telefone_loja", nullable=false, length=60)
    public String getGmeTelefoneLoja() {
        return this.gmeTelefoneLoja;
    }
    
    public void setGmeTelefoneLoja(String gmeTelefoneLoja) {
        this.gmeTelefoneLoja = gmeTelefoneLoja;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="gme_data_cadastro", nullable=false, length=10)
    public Date getGmeDataCadastro() {
        return this.gmeDataCadastro;
    }
    
    public void setGmeDataCadastro(Date gmeDataCadastro) {
        this.gmeDataCadastro = gmeDataCadastro;
    }

    
    @Column(name="gme_cnpj", nullable=false, length=18)
    public String getGmeCnpj() {
        return this.gmeCnpj;
    }
    
    public void setGmeCnpj(String gmeCnpj) {
        this.gmeCnpj = gmeCnpj;
    }

    
    @Column(name="gme_cep", nullable=false, length=9)
    public String getGmeCep() {
        return this.gmeCep;
    }
    
    public void setGmeCep(String gmeCep) {
        this.gmeCep = gmeCep;
    }

    
    @Column(name="gme_numero", nullable=false, length=6)
    public String getGmeNumero() {
        return this.gmeNumero;
    }
    
    public void setGmeNumero(String gmeNumero) {
        this.gmeNumero = gmeNumero;
    }






}


