package bean;
// Generated 11/12/2025 09:40:56 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Empresas generated by hbm2java
 */
@Entity
@Table(name = "empresas",
         catalog = "db_giuliano_eidt"
)
public class Empresas implements java.io.Serializable {

    private int gmeIdEmpresas;
    private String gmeNomeEmpresa;
    private String gmeCnpj;
    private String gmeCep;
    private String gmeNumero;
    private String gmeNomeRepresentante;
    private String gmeTelefoneRepresentante;
    private String gmeTelefoneEmpresa;

    public Empresas() {
    }

    public Empresas(String gmeNomeEmpresa, String gmeCnpj, String gmeCep, String gmeNumero, String gmeNomeRepresentante, String gmeTelefoneRepresentante, String gmeTelefoneEmpresa) {
        this.gmeNomeEmpresa = gmeNomeEmpresa;
        this.gmeCnpj = gmeCnpj;
        this.gmeCep = gmeCep;
        this.gmeNumero = gmeNumero;
        this.gmeNomeRepresentante = gmeNomeRepresentante;
        this.gmeTelefoneRepresentante = gmeTelefoneRepresentante;
        this.gmeTelefoneEmpresa = gmeTelefoneEmpresa;
    }

    public Empresas(String gmeNomeEmpresa, String gmeCnpj, String gmeCep, String gmeNumero, String gmeNomeRepresentante, String gmeTelefoneRepresentante, String gmeTelefoneEmpresa, Set vendas) {
        this.gmeNomeEmpresa = gmeNomeEmpresa;
        this.gmeCnpj = gmeCnpj;
        this.gmeCep = gmeCep;
        this.gmeNumero = gmeNumero;
        this.gmeNomeRepresentante = gmeNomeRepresentante;
        this.gmeTelefoneRepresentante = gmeTelefoneRepresentante;
        this.gmeTelefoneEmpresa = gmeTelefoneEmpresa;

    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "gme_id_empresas", unique = true, nullable = false)
    public int getGmeIdEmpresas() {
        return this.gmeIdEmpresas;
    }

    public void setGmeIdEmpresas(int gmeIdEmpresas) {
        this.gmeIdEmpresas = gmeIdEmpresas;
    }

    @Column(name = "gme_nome_empresa", nullable = false, length = 200)
    public String getGmeNomeEmpresa() {
        return this.gmeNomeEmpresa;
    }

    public void setGmeNomeEmpresa(String gmeNomeEmpresa) {
        this.gmeNomeEmpresa = gmeNomeEmpresa;
    }

    @Column(name = "gme_cnpj", nullable = false, length = 18)
    public String getGmeCnpj() {
        return this.gmeCnpj;
    }

    public void setGmeCnpj(String gmeCnpj) {
        this.gmeCnpj = gmeCnpj;
    }

    @Column(name = "gme_cep", nullable = false, length = 9)
    public String getGmeCep() {
        return this.gmeCep;
    }

    public void setGmeCep(String gmeCep) {
        this.gmeCep = gmeCep;
    }

    @Column(name = "gme_numero", nullable = false, length = 4)
    public String getGmeNumero() {
        return this.gmeNumero;
    }

    public void setGmeNumero(String gmeNumero) {
        this.gmeNumero = gmeNumero;
    }

    @Column(name = "gme_nome_representante", nullable = false, length = 100)
    public String getGmeNomeRepresentante() {
        return this.gmeNomeRepresentante;
    }

    public void setGmeNomeRepresentante(String gmeNomeRepresentante) {
        this.gmeNomeRepresentante = gmeNomeRepresentante;
    }

    @Column(name = "gme_telefone_representante", nullable = false, length = 20)
    public String getGmeTelefoneRepresentante() {
        return this.gmeTelefoneRepresentante;
    }

    public void setGmeTelefoneRepresentante(String gmeTelefoneRepresentante) {
        this.gmeTelefoneRepresentante = gmeTelefoneRepresentante;
    }

    @Column(name = "gme_telefone_empresa", nullable = false, length = 20)
    public String getGmeTelefoneEmpresa() {
        return this.gmeTelefoneEmpresa;
    }

    public void setGmeTelefoneEmpresa(String gmeTelefoneEmpresa) {
        this.gmeTelefoneEmpresa = gmeTelefoneEmpresa;
    }

    @Override
    public String toString() {
        return this.gmeNomeEmpresa;
    }

    @Override
    public boolean equals(Object object) {
        if (object instanceof Empresas) {
            Empresas empresas = (Empresas) object;
            if (this.getGmeIdEmpresas() == empresas.getGmeIdEmpresas()) {
                return true;
            }
        }
        return false;
    }

}
