package bean;
// Generated 12/12/2025 17:12:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Produtos generated by hbm2java
 */
@Entity
@Table(name="produtos"
    ,catalog="db_giuliano_eidt"
)
public class Produtos  implements java.io.Serializable {


     private int gmeIdProdutos;
     private String gmeNomeProduto;
     private String gmeSabor;
     private double gmeValorUnitario;
     private int gmeLitragem;
     private char gmeEdicaoLimitada;
     private int gmeAcucar;
     private int gmeCategoria;
  

    public Produtos() {
    }

	
    public Produtos(String gmeNomeProduto, String gmeSabor, double gmeValorUnitario, int gmeLitragem, char gmeEdicaoLimitada, int gmeAcucar, int gmeCategoria) {
        this.gmeNomeProduto = gmeNomeProduto;
        this.gmeSabor = gmeSabor;
        this.gmeValorUnitario = gmeValorUnitario;
        this.gmeLitragem = gmeLitragem;
        this.gmeEdicaoLimitada = gmeEdicaoLimitada;
        this.gmeAcucar = gmeAcucar;
        this.gmeCategoria = gmeCategoria;
    }
    public Produtos(String gmeNomeProduto, String gmeSabor, double gmeValorUnitario, int gmeLitragem, char gmeEdicaoLimitada, int gmeAcucar, int gmeCategoria, Set vendaProdutos) {
       this.gmeNomeProduto = gmeNomeProduto;
       this.gmeSabor = gmeSabor;
       this.gmeValorUnitario = gmeValorUnitario;
       this.gmeLitragem = gmeLitragem;
       this.gmeEdicaoLimitada = gmeEdicaoLimitada;
       this.gmeAcucar = gmeAcucar;
       this.gmeCategoria = gmeCategoria;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="gme_id_produtos", unique=true, nullable=false)
    public int getGmeIdProdutos() {
        return this.gmeIdProdutos;
    }
    
    public void setGmeIdProdutos(int gmeIdProdutos) {
        this.gmeIdProdutos = gmeIdProdutos;
    }

    
    @Column(name="gme_nome_produto", nullable=false, length=55)
    public String getGmeNomeProduto() {
        return this.gmeNomeProduto;
    }
    
    public void setGmeNomeProduto(String gmeNomeProduto) {
        this.gmeNomeProduto = gmeNomeProduto;
    }

    
    @Column(name="gme_sabor", nullable=false, length=55)
    public String getGmeSabor() {
        return this.gmeSabor;
    }
    
    public void setGmeSabor(String gmeSabor) {
        this.gmeSabor = gmeSabor;
    }

    
    @Column(name="gme_valor_unitario", nullable=false, precision=10)
    public double getGmeValorUnitario() {
        return this.gmeValorUnitario;
    }
    
    public void setGmeValorUnitario(double gmeValorUnitario) {
        this.gmeValorUnitario = gmeValorUnitario;
    }

    
    @Column(name="gme_litragem", nullable=false)
    public int getGmeLitragem() {
        return this.gmeLitragem;
    }
    
    public void setGmeLitragem(int gmeLitragem) {
        this.gmeLitragem = gmeLitragem;
    }

    
    @Column(name="gme_edicao_limitada", nullable=false, length=1)
    public char getGmeEdicaoLimitada() {
        return this.gmeEdicaoLimitada;
    }
    
    public void setGmeEdicaoLimitada(char gmeEdicaoLimitada) {
        this.gmeEdicaoLimitada = gmeEdicaoLimitada;
    }

    
    @Column(name="gme_acucar", nullable=false)
    public int getGmeAcucar() {
        return this.gmeAcucar;
    }
    
    public void setGmeAcucar(int gmeAcucar) {
        this.gmeAcucar = gmeAcucar;
    }

    
    @Column(name="gme_categoria", nullable=false)
    public int getGmeCategoria() {
        return this.gmeCategoria;
    }
    
    public void setGmeCategoria(int gmeCategoria) {
        this.gmeCategoria = gmeCategoria;
    }

    @Override
    public String toString() {
        return this.gmeNomeProduto;
    }

    @Override
    public boolean equals(Object object) {
        if (object instanceof Produtos) {
            Produtos produtos = (Produtos) object;
            if (this.getGmeIdProdutos()== produtos.getGmeIdProdutos()) {
                return true;
            }
        }
        return false;
    }
    
}


