package bean;
// Generated 12/12/2025 17:12:25 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name="usuarios"
    ,catalog="db_giuliano_eidt"
)
public class Usuarios  implements java.io.Serializable {


     private int gmeIdUsuarios;
     private String gmeApelido;
     private String gmeCpf;
     private String gmeNome;
     private Date gmeDatanasc;
     private String gmeSenha;
     private int gmeNivel;
     private char gmeAtivo;

    public Usuarios() {
    }

    public Usuarios(String gmeApelido, String gmeCpf, String gmeNome, Date gmeDatanasc, String gmeSenha, int gmeNivel, char gmeAtivo) {
       this.gmeApelido = gmeApelido;
       this.gmeCpf = gmeCpf;
       this.gmeNome = gmeNome;
       this.gmeDatanasc = gmeDatanasc;
       this.gmeSenha = gmeSenha;
       this.gmeNivel = gmeNivel;
       this.gmeAtivo = gmeAtivo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="gme_id_usuarios", unique=true, nullable=false)
    public int getGmeIdUsuarios() {
        return this.gmeIdUsuarios;
    }
    
    public void setGmeIdUsuarios(int gmeIdUsuarios) {
        this.gmeIdUsuarios = gmeIdUsuarios;
    }

    
    @Column(name="gme_apelido", nullable=false, length=25)
    public String getGmeApelido() {
        return this.gmeApelido;
    }
    
    public void setGmeApelido(String gmeApelido) {
        this.gmeApelido = gmeApelido;
    }

    
    @Column(name="gme_cpf", nullable=false, length=14)
    public String getGmeCpf() {
        return this.gmeCpf;
    }
    
    public void setGmeCpf(String gmeCpf) {
        this.gmeCpf = gmeCpf;
    }

    
    @Column(name="gme_nome", nullable=false, length=200)
    public String getGmeNome() {
        return this.gmeNome;
    }
    
    public void setGmeNome(String gmeNome) {
        this.gmeNome = gmeNome;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="gme_datanasc", nullable=false, length=10)
    public Date getGmeDatanasc() {
        return this.gmeDatanasc;
    }
    
    public void setGmeDatanasc(Date gmeDatanasc) {
        this.gmeDatanasc = gmeDatanasc;
    }

    
    @Column(name="gme_senha", nullable=false, length=30)
    public String getGmeSenha() {
        return this.gmeSenha;
    }
    
    public void setGmeSenha(String gmeSenha) {
        this.gmeSenha = gmeSenha;
    }

    
    @Column(name="gme_nivel", nullable=false)
    public int getGmeNivel() {
        return this.gmeNivel;
    }
    
    public void setGmeNivel(int gmeNivel) {
        this.gmeNivel = gmeNivel;
    }

    
    @Column(name="gme_ativo", nullable=false, length=1)
    public char getGmeAtivo() {
        return this.gmeAtivo;
    }
    
    public void setGmeAtivo(char gmeAtivo) {
        this.gmeAtivo = gmeAtivo;
    }
    @Override
    public String toString() {
        return this.gmeNome;
    }

    @Override
    public boolean equals(Object object) {
        if (object instanceof Clientes) {
            Usuarios usuarios = (Usuarios) object;
            if (this.getGmeIdUsuarios()== usuarios.getGmeIdUsuarios()) {
                return true;
            }
        }
        return false;
    }


}


