package bean;
// Generated 11/12/2025 09:40:56 by Hibernate Tools 4.3.1



import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Venda generated by hbm2java
 */
@Entity
@Table(name="venda"
    ,catalog="db_giuliano_eidt"
)
public class Venda  implements java.io.Serializable {


     private int gmeIdVenda;
     private Clientes clientes;
     private Empresas empresas;
     private Usuarios usuarios;
     private Date gmeData;
     private double gmeTotal;
    

    public Venda() {
    }

	
    public Venda(Clientes clientes, Empresas empresas, Usuarios usuarios, Date gmeData, double gmeTotal) {
        this.clientes = clientes;
        this.empresas = empresas;
        this.usuarios = usuarios;
        this.gmeData = gmeData;
        this.gmeTotal = gmeTotal;
    }
    public Venda(Clientes clientes, Empresas empresas, Usuarios usuarios, Date gmeData, double gmeTotal, Set vendaProdutos) {
       this.clientes = clientes;
       this.empresas = empresas;
       this.usuarios = usuarios;
       this.gmeData = gmeData;
       this.gmeTotal = gmeTotal;
      
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="gme_id_venda", unique=true, nullable=false)
    public int getGmeIdVenda() {
        return this.gmeIdVenda;
    }
    
    public void setGmeIdVenda(int gmeIdVenda) {
        this.gmeIdVenda = gmeIdVenda;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="gme_fk_clientes", nullable=false)
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="gme_fk_empresas", nullable=false)
    public Empresas getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Empresas empresas) {
        this.empresas = empresas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="gme_fk_usuarios", nullable=false)
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="gme_data", nullable=false, length=10)
    public Date getGmeData() {
        return this.gmeData;
    }
    
    public void setGmeData(Date gmeData) {
        this.gmeData = gmeData;
    }

    
    @Column(name="gme_total", nullable=false, precision=11)
    public double getGmeTotal() {
        return this.gmeTotal;
    }
    
    public void setGmeTotal(double gmeTotal) {
        this.gmeTotal = gmeTotal;
    }






}


