package bean;
// Generated 12/12/2025 17:12:25 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VendaProduto generated by hbm2java
 */
@Entity
@Table(name="venda_produto"
    ,catalog="db_giuliano_eidt"
)
public class VendaProduto  implements java.io.Serializable {


     private int gmeIdVendaProduto;
     private Produtos produtos;
     private Venda venda;
     private int gmeQuantidade;
     private double gmeValorUnitario;
     private double gmeValorTotal;

    public VendaProduto() {
    }

    public VendaProduto(Produtos produtos, Venda venda, int gmeQuantidade, double gmeValorUnitario, double gmeValorTotal) {
       this.produtos = produtos;
       this.venda = venda;
       this.gmeQuantidade = gmeQuantidade;
       this.gmeValorUnitario = gmeValorUnitario;
       this.gmeValorTotal = gmeValorTotal;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="gme_id_venda_produto", unique=true, nullable=false)
    public int getGmeIdVendaProduto() {
        return this.gmeIdVendaProduto;
    }
    
    public void setGmeIdVendaProduto(int gmeIdVendaProduto) {
        this.gmeIdVendaProduto = gmeIdVendaProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="gme_fk_produtos", nullable=false)
    public Produtos getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Produtos produtos) {
        this.produtos = produtos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="gme_fk_venda", nullable=false)
    public Venda getVenda() {
        return this.venda;
    }
    
    public void setVenda(Venda venda) {
        this.venda = venda;
    }

    
    @Column(name="gme_quantidade", nullable=false)
    public int getGmeQuantidade() {
        return this.gmeQuantidade;
    }
    
    public void setGmeQuantidade(int gmeQuantidade) {
        this.gmeQuantidade = gmeQuantidade;
    }

    
    @Column(name="gme_valor_unitario", nullable=false, precision=4)
    public double getGmeValorUnitario() {
        return this.gmeValorUnitario;
    }
    
    public void setGmeValorUnitario(double gmeValorUnitario) {
        this.gmeValorUnitario = gmeValorUnitario;
    }

    
    @Column(name="gme_valor_total", nullable=false, precision=11)
    public double getGmeValorTotal() {
        return this.gmeValorTotal;
    }
    
    public void setGmeValorTotal(double gmeValorTotal) {
        this.gmeValorTotal = gmeValorTotal;
    }

}


